# run_all.R — execute every chapter script in book order.
# Generated by scripts/extract_code.R --standalone; do not edit by hand.
# Usage: from the bundle root,  Rscript run_all.R
scripts <- list.files("code", pattern = "\\.R$", full.names = TRUE)
for (s in scripts) {
  cat("==", s, "\n")
  source(s, local = new.env())
}

