# Introduction to Pharmacokinetics
# Extracted executable R code from 01-introduction.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Preview: Exponential Decline
# ----------------------------------------------------------------------
library(ggplot2)
time <- seq(0, 24, by = 0.1)
conc <- 5 * exp(-0.2 * time)
ggplot(data.frame(time, conc), aes(time, conc)) +
  geom_line(linewidth = 1) +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = "Prototypical one-compartment IV bolus profile"
  ) +
  theme_bw()

