# Mathematical Foundations of Pharmacokinetics
# Extracted executable R code from 02-mathematical-foundations.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Example
# ----------------------------------------------------------------------
k <- 0.20
A0 <- 100

time <- seq(0, 24, by = 0.1)

A <- A0 * exp(-k * time)

plot(
  time,
  A,
  type = "l",
  lwd = 2,
  xlab = "Time (h)",
  ylab = "Amount (mg)"
)

