# Differential Equations in Pharmacokinetics
# Extracted executable R code from 03-differential-equations.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Solving an ODE in R
# ----------------------------------------------------------------------
library(deSolve)

model <- function(t, state, parms){

    with(as.list(c(state,parms)),{

        dA <- -k*A

        list(c(dA))

    })

}

times <- seq(0,24,0.1)

out <- ode(
    y=c(A=100),
    times=times,
    func=model,
    parms=c(k=0.2)
)

head(out)

