# Compartment Models
# Extracted executable R code from 04-compartment-models.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Illustration: One- versus Two-Compartment Profiles
# ----------------------------------------------------------------------
library(ggplot2)

set.seed(20260731)
time <- seq(0, 24, by = 0.1)

# One-compartment IV bolus
C1 <- 5 * exp(-0.2 * time)

# Two-compartment biexponential (illustrative)
C2 <- 3.5 * exp(-1.2 * time) + 1.5 * exp(-0.15 * time)

df <- rbind(
  data.frame(time = time, conc = C1, model = "One-compartment"),
  data.frame(time = time, conc = C2, model = "Two-compartment")
)

ggplot(df, aes(time, conc, color = model)) +
  geom_line(linewidth = 1) +
  scale_y_log10() +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    color = NULL,
    title = "Distribution phase appears only in multi-compartment kinetics"
  ) +
  theme_bw() +
  theme(legend.position = "bottom")

