# One-Compartment Model: Intravenous Bolus Administration
# Extracted executable R code from 05-one-compartment-iv-bolus.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Simulation in R
# ----------------------------------------------------------------------

library(ggplot2)

dose <- 100

V <- 20

k <- 0.18

time <- seq(0,24,0.1)

conc <- dose/V*exp(-k*time)

ggplot(
    data.frame(time,conc),
    aes(time,conc)
)+
geom_line(linewidth=1)+
labs(
    x="Time (h)",
    y="Concentration (mg/L)"
)

