# Fundamental Pharmacokinetic Parameters
# Extracted executable R code from 06-fundamental-pk-parameters.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Example
# ----------------------------------------------------------------------
library(ggplot2)
dose <- 100
V    <- 20
k    <- 0.15

CL   <- k * V
t12  <- log(2) / k
AUC  <- dose / CL
MRT  <- 1 / k

print(data.frame(
  Parameter = c("CL (L/h)", "Half-life (h)", "AUC (mg·h/L)", "MRT (h)"),
  Value = round(c(CL, t12, AUC, MRT), 3)
))

time <- seq(0, 24, 0.1)
conc <- (dose / V) * exp(-k * time)
ggplot(data.frame(time, conc), aes(time, conc)) +
  geom_line(linewidth = 1) +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = expression(C(t) == C[0] * e^{-k*t})) +
  theme_bw()

