# Parameter Estimation from Concentration–Time Data
# Extracted executable R code from 07-parameter-estimation.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Linear Regression in R
# ----------------------------------------------------------------------
pk <- data.frame(

time=c(0,1,2,4,6,8,12),

conc=c(5,4.2,3.5,2.45,1.70,1.20,0.60)

)

fit <- lm(log(conc)~time,data=pk)

summary(fit)

coef(fit)

# ----------------------------------------------------------------------
# Section: Linear Regression in R
# ----------------------------------------------------------------------
k <- -coef(fit)[2]

# ----------------------------------------------------------------------
# Section: Nonlinear Least Squares
# ----------------------------------------------------------------------
nlsfit <- nls(
  conc ~ C0 * exp(-k * time),
  data = pk,
  start = list(C0 = 5, k = 0.15)
)
summary(nlsfit)

# ----------------------------------------------------------------------
# Section: Nonlinear Least Squares
# ----------------------------------------------------------------------
library(ggplot2)
pk$pred <- predict(nlsfit)
ggplot(pk, aes(time, conc)) +
  geom_point(size = 2) +
  geom_line(aes(y = pred), linewidth = 1, color = "steelblue") +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Nonlinear least-squares fit of one-compartment IV bolus") +
  theme_bw()

