# Area Under the Concentration–Time Curve (AUC)
# Extracted executable R code from 08-area-under-the-curve.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Example
# ----------------------------------------------------------------------
pk <-
data.frame(

time=c(0,2,4,6,8),

conc=c(5,3.4,2.3,1.6,1.1)

)

dt <- diff(pk$time)

avg <- (head(pk$conc, -1) + tail(pk$conc, -1)) / 2

sum(avg * dt)

