# Statistical Moments in Pharmacokinetics
# Extracted executable R code from 08a-statistical-moments.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Example: Moments from a Profile {#sec-moments-r}
# ----------------------------------------------------------------------
library(ggplot2)

k <- 0.15
C0 <- 5
D <- 100
t <- seq(0, 24, by = 0.5)
C <- C0 * exp(-k * t)

# Trapezoidal moments on the observed grid
trap_moment <- function(time, conc, power = 0) {
  y <- (time^power) * conc
  sum(diff(time) * (head(y, -1) + tail(y, -1)) / 2)
}

AUC_obs <- trap_moment(t, C, 0)
AUMC_obs <- trap_moment(t, C, 1)
M2_obs <- trap_moment(t, C, 2)

# Extrapolate from t_last using known terminal slope k
t_last <- max(t)
C_last <- C0 * exp(-k * t_last)
AUC_inf <- AUC_obs + C_last / k
AUMC_inf <- AUMC_obs + t_last * C_last / k + C_last / k^2
M2_inf <- M2_obs + t_last^2 * C_last / k +
  2 * t_last * C_last / k^2 + 2 * C_last / k^3

MRT <- AUMC_inf / AUC_inf
VRT <- M2_inf / AUC_inf - MRT^2
CL <- D / AUC_inf
Vss <- CL * MRT

data.frame(
  AUC = round(AUC_inf, 2),
  AUMC = round(AUMC_inf, 2),
  MRT = round(MRT, 3),
  VRT = round(VRT, 3),
  CL = round(CL, 3),
  Vss = round(Vss, 2),
  MRT_true = 1 / k,
  VRT_true = 1 / k^2,
  V_true = D / C0
)

# ----------------------------------------------------------------------
# Section: R Example: Moments from a Profile {#sec-moments-r}
# ----------------------------------------------------------------------
df <- data.frame(
  time = t,
  C = C,
  tC = t * C
)

ggplot(df, aes(time)) +
  geom_line(aes(y = C, color = "C(t)")) +
  geom_line(aes(y = tC / max(tC) * max(C), color = "t C(t) (scaled)")) +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    color = NULL,
    title = "Zeroth- and first-moment integrands"
  ) +
  theme_bw() +
  theme(legend.position = "bottom")

