# Pharmacokinetic Study Design and Sampling
# Extracted executable R code from 09-pharmacokinetic-study-design.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Illustration
# ----------------------------------------------------------------------
library(ggplot2)

time <- seq(0,24,0.1)

conc <- 5*exp(-0.15*time)

sample_times <-
c(0,0.5,1,2,4,8,12,24)

ggplot(
data.frame(time,conc),
aes(time,conc)
)+
geom_line(linewidth=1)+
geom_point(
data=data.frame(
time=sample_times,
conc=5*exp(-0.15*sample_times)
),
size=3
)+
labs(
x="Time (h)",
y="Concentration (mg/L)"
)

