# Clinical Pharmacokinetic Data
# Extracted executable R code from 10-clinical-pharmacokinetic-data.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Example PK Dataset
# ----------------------------------------------------------------------
pk_ex <- read.csv("data/pk_iv_bolus.csv", stringsAsFactors = FALSE)
pk_ex <- pk_ex[as.character(pk_ex$USUBJID) == "101", c("USUBJID", "TIME", "CONC", "DOSE")]
knitr::kable(
  pk_ex,
  col.names = c("USUBJID", "TIME (h)", "CONC (mg/L)", "DOSE (mg)"),
  digits = 3
)

# ----------------------------------------------------------------------
# Section: Data Preparation in R
# ----------------------------------------------------------------------
library(dplyr)
library(readr)
library(ggplot2)

pk <- read_csv("data/pk_iv_bolus.csv", show_col_types = FALSE) %>%
  mutate(
    TIME = as.numeric(TIME),
    CONC = as.numeric(CONC),
    DOSE = as.numeric(DOSE)
  ) %>%
  arrange(USUBJID, TIME)

pk

# ----------------------------------------------------------------------
# Section: Data Preparation in R
# ----------------------------------------------------------------------
pk %>%
  summarise(
    n_subjects = n_distinct(USUBJID),
    n_records = n(),
    missing_conc = sum(is.na(CONC)),
    min_time = min(TIME, na.rm = TRUE),
    max_time = max(TIME, na.rm = TRUE)
  )

# ----------------------------------------------------------------------
# Section: Data Preparation in R
# ----------------------------------------------------------------------
ggplot(pk, aes(TIME, CONC)) +
  geom_point(size = 2) +
  geom_line() +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Example IV bolus concentration–time profile") +
  theme_bw()

# ----------------------------------------------------------------------
# Section: Data Preparation in R
# ----------------------------------------------------------------------
LLOQ <- 0.5
pk_blq <- pk %>%
  mutate(
    BLQ = CONC < LLOQ,
    CONC_M5 = ifelse(BLQ, LLOQ / 2, CONC)
  )
pk_blq %>% select(TIME, CONC, BLQ, CONC_M5)

