# Intravenous Infusion
# Extracted executable R code from 11-intravenous-infusion.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Implementation
# ----------------------------------------------------------------------
library(ggplot2)
library(dplyr)

set.seed(20260731)

# --- Parameters ---
R0   <- 100          # mg/h infusion rate
CL   <- 5            # L/h
V    <- 20           # L
k    <- CL / V       # h^-1
t12  <- 0.693 / k
Tinf <- 8            # h infusion duration
Css  <- R0 / CL

# --- Analytical function: infusion + post-infusion ---
conc_infusion <- function(t, R0, CL, V, Tinf) {
  k <- CL / V
  Css <- R0 / CL
  ifelse(
    t <= Tinf,
    Css * (1 - exp(-k * t)),
    Css * (1 - exp(-k * Tinf)) * exp(-k * (t - Tinf))
  )
}

time <- seq(0, 24, 0.05)
conc <- conc_infusion(time, R0, CL, V, Tinf)

df <- data.frame(time = time, conc = conc)

# --- Steady-state attainment curve ---
n_hl <- seq(0, 6, 0.01)
f_ss <- 1 - exp(-k * n_hl * t12)
df_ss <- data.frame(half_lives = n_hl, fraction = f_ss)

# ----------------------------------------------------------------------
# Section: Concentration-time profile
# ----------------------------------------------------------------------
ggplot(df, aes(time, conc)) +
  geom_line(linewidth = 1, color = "steelblue") +
  geom_hline(yintercept = Css, linetype = "dashed", color = "red") +
  geom_vline(xintercept = Tinf, linetype = "dotted") +
  annotate("text", x = Tinf + 0.5, y = Css + 0.3,
           label = paste("Css =", round(Css, 1), "mg/L"), hjust = 0) +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = "IV Infusion: During and After Infusion"
  )

# ----------------------------------------------------------------------
# Section: Fraction of steady state versus half-lives
# ----------------------------------------------------------------------
ggplot(df_ss, aes(half_lives, fraction)) +
  geom_line(linewidth = 1) +
  geom_hline(yintercept = c(0.5, 0.75, 0.875, 0.94, 0.97),
             linetype = "dashed", alpha = 0.5) +
  geom_vline(xintercept = 1:5, linetype = "dotted", alpha = 0.4) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    x = "Half-lives",
    y = "Fraction of Css",
    title = "Approach to Steady State During Infusion"
  )

# ----------------------------------------------------------------------
# Section: Loading dose effect
# ----------------------------------------------------------------------
C_ld <- Css
time_ld <- seq(0, 24, 0.05)

conc_no_ld <- conc_infusion(time_ld, R0, CL, V, Tinf = 24)
# With LD: C(0) = LD/V = Css, then the maintenance infusion keeps Css
conc_with_ld <- rep(Css, length(time_ld))

df_ld <- data.frame(
  time = rep(time_ld, 2),
  conc = c(conc_no_ld, conc_with_ld),
  scenario = rep(c("No loading dose", "With loading dose"), each = length(time_ld))
)

ggplot(df_ld, aes(time, conc, color = scenario)) +
  geom_line(linewidth = 1) +
  geom_hline(yintercept = Css, linetype = "dashed", alpha = 0.5) +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Effect of Loading Dose on Infusion") +
  scale_color_brewer(palette = "Set1")

# ----------------------------------------------------------------------
# Section: Simulated data with estimation
# ----------------------------------------------------------------------
library(deSolve)

# ODE verification with deSolve
infusion_ode <- function(t, state, parms) {
  k <- parms["k"]
  R0 <- parms["R0"]
  Tinf <- parms["Tinf"]
  rate <- if (t <= Tinf) R0 else 0
  dA <- rate - k * state["A"]
  list(c(dA))
}

parms <- c(k = k, R0 = R0, Tinf = Tinf)
times_ode <- seq(0, 24, 0.1)
out <- ode(y = c(A = 0), times = times_ode, func = infusion_ode,
           parms = parms)
out_df <- data.frame(time = out[, "time"], conc_ode = out[, "A"] / V)

# Add proportional error
conc_obs <- conc_infusion(out_df$time, R0, CL, V, Tinf)
conc_obs <- conc_obs * exp(rnorm(length(conc_obs), 0, 0.05))
idx <- seq(1, length(conc_obs), by = 3)
obs_df <- data.frame(time = out_df$time[idx], conc = conc_obs[idx])

# Estimate Css from late infusion samples
Css_est <- mean(obs_df$conc[obs_df$time >= 6 & obs_df$time <= Tinf])
CL_est <- R0 / Css_est
cat("Estimated Css:", round(Css_est, 2), "mg/L\n")
cat("Estimated CL:", round(CL_est, 2), "L/h\n")
cat("True CL:", CL, "L/h\n")

