# Oral Administration: Absorption and Bioavailability
# Extracted executable R code from 12-oral-administration.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Implementation
# ----------------------------------------------------------------------
library(ggplot2)
library(dplyr)

set.seed(20260731)

# --- Standard oral parameters ---
Dose <- 100
F    <- 0.90
V    <- 25
ka   <- 1.2
k    <- 0.15

# --- Bateman function ---
bateman <- function(t, Dose, F, V, ka, k) {
  (F * Dose * ka / (V * (ka - k))) * (exp(-k * t) - exp(-ka * t))
}

# --- Derived metrics ---
Tmax <- log(ka / k) / (ka - k)
Cmax <- bateman(Tmax, Dose, F, V, ka, k)
t12_elim <- 0.693 / k

cat("Tmax:", round(Tmax, 2), "h\n")
cat("Cmax:", round(Cmax, 2), "mg/L\n")
cat("Elimination t1/2:", round(t12_elim, 2), "h\n")

# ----------------------------------------------------------------------
# Section: Standard oral profile
# ----------------------------------------------------------------------
time <- seq(0, 24, 0.05)
conc <- bateman(time, Dose, F, V, ka, k)

df <- data.frame(time = time, conc = conc)

ggplot(df, aes(time, conc)) +
  geom_line(linewidth = 1, color = "steelblue") +
  geom_vline(xintercept = Tmax, linetype = "dashed", color = "red") +
  geom_hline(yintercept = Cmax, linetype = "dotted", color = "red", alpha = 0.5) +
  annotate("point", x = Tmax, y = Cmax, size = 3, color = "red") +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = "Oral Absorption: Bateman Profile"
  )

# ----------------------------------------------------------------------
# Section: Flip-flop kinetics illustration
# ----------------------------------------------------------------------
# Normal: ka > k
ka_normal <- 1.2
k_normal  <- 0.15

# Flip-flop: ka < k
ka_flip <- 0.10
k_flip  <- 0.50

time_ff <- seq(0, 48, 0.1)

df_ff <- data.frame(
  time = rep(time_ff, 2),
  conc = c(
    bateman(time_ff, Dose, F, V, ka_normal, k_normal),
    bateman(time_ff, Dose, F, V, ka_flip, k_flip)
  ),
  scenario = rep(c("Normal (ka > k)", "Flip-flop (ka < k)"), each = length(time_ff))
)

# Terminal half-lives
t12_normal <- 0.693 / k_normal
t12_flip   <- 0.693 / ka_flip  # terminal slope is ka, not k

cat("Normal terminal t1/2 (elimination):", round(t12_normal, 2), "h\n")
cat("Flip-flop apparent t1/2 (absorption):", round(t12_flip, 2), "h\n")
cat("True elimination t1/2 in flip-flop:", round(0.693 / k_flip, 2), "h\n")

ggplot(df_ff, aes(time, conc, color = scenario)) +
  geom_line(linewidth = 1) +
  scale_y_log10() +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = "Flip-Flop Kinetics: Terminal Slope Misidentification",
    color = "Scenario"
  ) +
  scale_color_brewer(palette = "Set1")

# ----------------------------------------------------------------------
# Section: Lag time illustration
# ----------------------------------------------------------------------
tlag <- 1.5  # h

bateman_lag <- function(t, Dose, F, V, ka, k, tlag) {
  t_eff <- pmax(0, t - tlag)
  ifelse(t <= tlag, 0, bateman(t_eff, Dose, F, V, ka, k))
}

time_lag <- seq(0, 24, 0.05)
conc_no_lag <- bateman(time_lag, Dose, F, V, ka, k)
conc_lag    <- bateman_lag(time_lag, Dose, F, V, ka, k, tlag)

df_lag <- data.frame(
  time = rep(time_lag, 2),
  conc = c(conc_no_lag, conc_lag),
  model = rep(c("No lag", paste0("Lag = ", tlag, " h")), each = length(time_lag))
)

ggplot(df_lag, aes(time, conc, color = model)) +
  geom_line(linewidth = 1) +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = "Effect of Absorption Lag Time",
    color = "Model"
  ) +
  scale_color_brewer(palette = "Set1")

# ----------------------------------------------------------------------
# Section: Simulated data with NLS estimation
# ----------------------------------------------------------------------
# Generate noisy observations
conc_true <- bateman(time, Dose, F, V, ka, k)
conc_obs  <- conc_true * exp(rnorm(length(time), 0, 0.08))
idx <- seq(1, length(time), by = 3)
obs_df <- data.frame(time = time[idx], conc = conc_obs[idx])

# NLS fit of Bateman function
fit <- nls(
  conc ~ A * (exp(-k * time) - exp(-ka * time)),
  data = obs_df,
  start = list(A = 3, k = 0.1, ka = 0.8),
  lower = c(0, 0.001, 0.001),
  algorithm = "port"
)

fit_coef <- coef(fit)
cat("\nNLS estimates:\n")
cat("A =", round(fit_coef["A"], 4), "\n")
cat("k =", round(fit_coef["k"], 4), "h^-1\n")
cat("ka =", round(fit_coef["ka"], 4), "h^-1\n")
cat("\nTrue values: k =", k, ", ka =", ka, "\n")

obs_df$pred <- predict(fit, newdata = obs_df)

ggplot(obs_df, aes(time, conc)) +
  geom_point(size = 2.5, color = "steelblue") +
  geom_line(aes(y = pred), linewidth = 1, color = "red") +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = "NLS Fit of Bateman Function to Simulated Oral Data"
  )

# ----------------------------------------------------------------------
# Section: Effect of absorption rate on profile
# ----------------------------------------------------------------------
ka_values <- c(0.3, 0.6, 1.2, 3.0)
df_ka <- do.call(rbind, lapply(ka_values, function(ka_val) {
  data.frame(
    time = time,
    conc = bateman(time, Dose, F, V, ka_val, k),
    ka = paste0("ka = ", ka_val, " h^-1")
  )
}))

ggplot(df_ka, aes(time, conc, color = ka)) +
  geom_line(linewidth = 1) +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = "Effect of Absorption Rate on Oral Profile",
    color = "Absorption rate"
  ) +
  scale_color_brewer(palette = "Set1")

# ----------------------------------------------------------------------
# Section: Bioavailability comparison
# ----------------------------------------------------------------------
# Simulate IV and oral profiles
D_iv <- 100
C_iv <- (D_iv / V) * exp(-k * time)
C_oral <- bateman(time, Dose, F, V, ka, k)

# AUC by trapezoidal rule
auc_iv   <- sum(diff(time) * (C_iv[-1] + C_iv[-length(C_iv)]) / 2)
auc_oral <- sum(diff(time) * (C_oral[-1] + C_oral[-length(C_oral)]) / 2)
F_est    <- (auc_oral / Dose) / (auc_iv / D_iv)

cat("AUC (IV):", round(auc_iv, 1), "mg·h/L\n")
cat("AUC (oral):", round(auc_oral, 1), "mg·h/L\n")
cat("Estimated F:", round(F_est, 3), "\n")
cat("True F:", F, "\n")

bio_df <- data.frame(
  time = rep(time, 2),
  conc = c(C_iv, C_oral),
  route = rep(c("IV bolus", "Oral"), each = length(time))
)

ggplot(bio_df, aes(time, conc, color = route)) +
  geom_line(linewidth = 1) +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = paste0("IV vs Oral (F = ", F, ")"),
    color = "Route"
  ) +
  scale_color_brewer(palette = "Set1")

# ----------------------------------------------------------------------
# Section: ODE verification with deSolve
# ----------------------------------------------------------------------
library(deSolve)

oral_ode <- function(t, state, parms) {
  ka <- parms["ka"]; k <- parms["k"]; F <- parms["F"]
  Ag <- state["Ag"]; Ac <- state["Ac"]
  dAg <- -ka * Ag
  dAc <- F * ka * Ag - k * Ac
  list(c(dAg, dAc))
}

parms_ode <- c(ka = ka, k = k, F = F)
out <- ode(
  y = c(Ag = Dose, Ac = 0),
  times = time,
  func = oral_ode,
  parms = parms_ode
)

ode_df <- data.frame(
  time = out[, "time"],
  conc_ode = out[, "Ac"] / V
)

ggplot() +
  geom_line(data = df, aes(time, conc), linewidth = 1, color = "steelblue") +
  geom_point(data = ode_df[seq(1, nrow(ode_df), 20), ],
             aes(time, conc_ode), color = "red", size = 1.5) +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = "Bateman Function vs deSolve ODE Verification"
  )

