# Multiple-Dose Pharmacokinetics
# Extracted executable R code from 13-multiple-dosing.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Implementation
# ----------------------------------------------------------------------
library(ggplot2)
library(dplyr)

set.seed(20260731)

# --- Parameters ---
D     <- 500          # mg
V     <- 30           # L
CL    <- 3            # L/h
k     <- CL / V
t12   <- 0.693 / k
tau   <- 8            # h dosing interval
n_doses <- 8

# --- Single dose profile ---
C_single <- function(t, D, V, k) {
  (D / V) * exp(-k * t)
}

# --- Multiple dose by superposition ---
C_multidose <- function(t, D, V, k, tau, n_doses) {
  sapply(t, function(ti) {
    sum(sapply(0:(n_doses - 1), function(j) {
      tj <- ti - j * tau
      if (tj >= 0) C_single(tj, D, V, k) else 0
    }))
  })
}

# --- Steady-state analytical ---
Rac <- 1 / (1 - exp(-k * tau))
Css_max <- (D / V) * Rac
Css_min <- (D / V) * exp(-k * tau) / (1 - exp(-k * tau))
Css_avg <- D / (CL * tau)

cat("Accumulation ratio:", round(Rac, 3), "\n")
cat("Css,max:", round(Css_max, 2), "mg/L\n")
cat("Css,min:", round(Css_min, 2), "mg/L\n")
cat("Css,avg:", round(Css_avg, 2), "mg/L\n")

# ----------------------------------------------------------------------
# Section: Multiple-dose concentration-time profile
# ----------------------------------------------------------------------
total_time <- n_doses * tau + tau
time <- seq(0, total_time, 0.05)
conc <- C_multidose(time, D, V, k, tau, n_doses)

df <- data.frame(time = time, conc = conc)

# Mark dose times
dose_times <- seq(0, (n_doses - 1) * tau, by = tau)

ggplot(df, aes(time, conc)) +
  geom_line(linewidth = 1, color = "steelblue") +
  geom_vline(xintercept = dose_times, linetype = "dotted", alpha = 0.5) +
  geom_hline(yintercept = c(Css_max, Css_min, Css_avg),
             linetype = c("solid", "dashed", "dotted"),
             color = c("red", "orange", "darkgreen"), alpha = 0.7) +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = paste0("Multiple IV Bolus Doses (D = ", D, " mg, tau = ", tau, " h)")
  )

# ----------------------------------------------------------------------
# Section: Accumulation over successive doses
# ----------------------------------------------------------------------
peak_conc <- sapply(0:(n_doses - 1), function(j) {
  C_multidose(j * tau, D, V, k, tau, j + 1)
})

df_acc <- data.frame(
  dose_number = 1:n_doses,
  peak = peak_conc,
  ss_peak = Css_max
)

ggplot(df_acc, aes(dose_number, peak)) +
  geom_line(linewidth = 1, color = "steelblue") +
  geom_point(size = 3, color = "steelblue") +
  geom_hline(yintercept = Css_max, linetype = "dashed", color = "red") +
  labs(
    x = "Dose number",
    y = "Peak concentration (mg/L)",
    title = "Accumulation Toward Steady State"
  )

# ----------------------------------------------------------------------
# Section: Effect of dosing interval
# ----------------------------------------------------------------------
tau_values <- c(4, 8, 12, 24)
df_tau <- do.call(rbind, lapply(tau_values, function(tv) {
  data.frame(
    time = time,
    conc = C_multidose(time, D, V, k, tv, n_doses),
    tau = paste0("tau = ", tv, " h")
  )
}))

ggplot(df_tau, aes(time, conc, color = tau)) +
  geom_line(linewidth = 1) +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Effect of Dosing Interval on Accumulation") +
  scale_color_brewer(palette = "Set1")

# ----------------------------------------------------------------------
# Section: Simulated trough data
# ----------------------------------------------------------------------
# Simulate trough samples at steady state
n_subj <- 20
trough_true <- Css_min
trough_obs <- trough_true * exp(rnorm(n_subj, 0, 0.15))

trough_df <- data.frame(subject = 1:n_subj, trough = trough_obs)

ggplot(trough_df, aes(subject, trough)) +
  geom_point(size = 3, color = "steelblue") +
  geom_hline(yintercept = Css_min, linetype = "dashed", color = "red") +
  labs(x = "Subject", y = "Trough concentration (mg/L)",
       title = "Simulated Steady-State Trough Concentrations")

