# Steady-State Pharmacokinetics
# Extracted executable R code from 14-steady-state.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Implementation
# ----------------------------------------------------------------------
library(ggplot2)
library(dplyr)

set.seed(20260731)

# --- Parameters ---
D     <- 200          # mg
Fbio  <- 0.85         # named Fbio, not F, which is base R's FALSE
V     <- 35           # L
CL    <- 4            # L/h
k     <- CL / V
t12   <- 0.693 / k
tau   <- 12           # h
MEC   <- 2.0          # mg/L minimum effective
MTC   <- 10.0         # mg/L minimum toxic

# --- Steady-state metrics ---
# Fbio enters every expression: only Fbio * D reaches the circulation per dose.
Cav_ss  <- Fbio * D / (CL * tau)
Rac     <- 1 / (1 - exp(-k * tau))
Css_max <- (Fbio * D / V) * Rac
Css_min <- (Fbio * D / V) * exp(-k * tau) / (1 - exp(-k * tau))
fluct   <- (Css_max - Css_min) / Cav_ss   # equals k * tau

cat("Cav,ss:", round(Cav_ss, 2), "mg/L\n")
cat("Css,max:", round(Css_max, 2), "mg/L\n")
cat("Css,min:", round(Css_min, 2), "mg/L\n")
cat("Fluctuation:", round(fluct, 2), "\n")
cat("Within window:", Css_min >= MEC & Css_max <= MTC, "\n")

# ----------------------------------------------------------------------
# Section: Steady-state profile with therapeutic window
# ----------------------------------------------------------------------
# Superposition function
C_multidose <- function(t, D, V, k, tau, n, Fbio = 1) {
  sapply(t, function(ti) {
    sum(sapply(0:(n - 1), function(j) {
      tj <- ti - j * tau
      if (tj >= 0) (Fbio * D / V) * exp(-k * tj) else 0
    }))
  })
}

n_doses <- 10
time <- seq(0, n_doses * tau, 0.05)
conc <- C_multidose(time, D, V, k, tau, n_doses, Fbio)

df <- data.frame(time = time, conc = conc)

# Highlight last interval
last_start <- (n_doses - 1) * tau
df_ss <- df %>% filter(time >= last_start)

ggplot(df, aes(time, conc)) +
  geom_line(linewidth = 0.8, color = "gray70") +
  geom_line(data = df_ss, aes(time, conc), linewidth = 1.2, color = "steelblue") +
  geom_hline(yintercept = c(MEC, MTC, Cav_ss),
             linetype = c("dashed", "dashed", "dotted"),
             color = c("green", "red", "blue"), alpha = 0.7) +
  annotate("rect", xmin = last_start, xmax = n_doses * tau,
           ymin = MEC, ymax = MTC, alpha = 0.1, fill = "green") +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Steady-State Profile with Therapeutic Window")

# ----------------------------------------------------------------------
# Section: Dosing interval optimization
# ----------------------------------------------------------------------
tau_range <- seq(4, 24, 0.5)
opt_df <- data.frame(
  tau = tau_range,
  Cav = Fbio * D / (CL * tau_range),
  Cmax = (Fbio * D / V) / (1 - exp(-k * tau_range)),
  Cmin = (Fbio * D / V) * exp(-k * tau_range) / (1 - exp(-k * tau_range))
) %>%
  mutate(
    fluctuation = (Cmax - Cmin) / Cav,
    in_window = Cmin >= MEC & Cmax <= MTC
  )

ggplot(opt_df, aes(tau, fluctuation, color = in_window)) +
  geom_line(linewidth = 1) +
  scale_color_manual(values = c("TRUE" = "green", "FALSE" = "red"),
                     labels = c("Outside", "Within window")) +
  labs(x = "Dosing interval (h)", y = "Fluctuation",
       title = "Fluctuation vs Dosing Interval",
       color = "Therapeutic window") +
  geom_vline(xintercept = tau, linetype = "dotted")

# ----------------------------------------------------------------------
# Section: Time to steady state
# ----------------------------------------------------------------------
n_hl <- seq(0, 6, 0.01)
f_ss <- 1 - exp(-k * n_hl * t12)

df_time <- data.frame(half_lives = n_hl, fraction = f_ss)

ggplot(df_time, aes(half_lives, fraction)) +
  geom_line(linewidth = 1) +
  geom_hline(yintercept = c(0.94, 0.97), linetype = "dashed", alpha = 0.5) +
  geom_vline(xintercept = c(4, 5), linetype = "dotted", alpha = 0.5) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Half-lives since regimen start",
       y = "Fraction of steady state",
       title = "Time to Steady State")

# ----------------------------------------------------------------------
# Section: Dose adjustment simulation
# ----------------------------------------------------------------------
D_old <- 200
C_trough_obs <- 1.5   # mg/L (below target)
C_target <- 3.0       # mg/L
D_new <- D_old * (C_target / C_trough_obs)

cat("Original dose:", D_old, "mg\n")
cat("Observed trough:", C_trough_obs, "mg/L\n")
cat("Target trough:", C_target, "mg/L\n")
cat("New dose:", round(D_new, 0), "mg\n")
cat("Wait", round(5 * t12, 1), "h before re-assessing\n")

