# Two-Compartment Pharmacokinetic Models
# Extracted executable R code from 15-two-compartment-models.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Implementation
# ----------------------------------------------------------------------
library(ggplot2)
library(deSolve)
library(dplyr)

set.seed(20260731)

# --- Microconstants ---
k10 <- 0.08    # h^-1
k12 <- 0.40    # h^-1
k21 <- 0.25    # h^-1
V1  <- 10      # L
D   <- 100     # mg

# --- Macroconstants ---
sum_k <- k10 + k12 + k21
disc  <- sum_k^2 - 4 * k10 * k21
alpha <- (sum_k + sqrt(disc)) / 2
beta  <- (sum_k - sqrt(disc)) / 2

t12_alpha <- 0.693 / alpha
t12_beta  <- 0.693 / beta

# --- Coefficients A, B ---
A_coef <- (D / V1) * (alpha - k21) / (alpha - beta)
B_coef <- (D / V1) * (k21 - beta) / (alpha - beta)

Vss <- V1 * (1 + k12 / k21)
CL  <- k10 * V1

cat("alpha:", round(alpha, 4), "h^-1, t1/2:", round(t12_alpha, 2), "h\n")
cat("beta:", round(beta, 4), "h^-1, t1/2:", round(t12_beta, 2), "h\n")
cat("V1:", V1, "L, Vss:", round(Vss, 1), "L, CL:", round(CL, 2), "L/h\n")
cat("A:", round(A_coef, 3), "B:", round(B_coef, 3), "mg/L\n")

# ----------------------------------------------------------------------
# Section: Closed-form concentration profile
# ----------------------------------------------------------------------
C_biexp <- function(t, A, B, alpha, beta) {
  A * exp(-alpha * t) + B * exp(-beta * t)
}

time <- seq(0, 48, 0.05)
conc <- C_biexp(time, A_coef, B_coef, alpha, beta)
df <- data.frame(time = time, conc = conc)

ggplot(df, aes(time, conc)) +
  geom_line(linewidth = 1, color = "steelblue") +
  scale_y_log10() +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Two-Compartment IV Bolus (Semi-Log)")

# ----------------------------------------------------------------------
# Section: ODE simulation with deSolve
# ----------------------------------------------------------------------
twocomp_ode <- function(t, state, parms) {
  k10 <- parms["k10"]; k12 <- parms["k12"]; k21 <- parms["k21"]
  A1 <- state["A1"]; A2 <- state["A2"]
  dA1 <- -(k10 + k12) * A1 + k21 * A2
  dA2 <- k12 * A1 - k21 * A2
  list(c(dA1, dA2))
}

parms <- c(k10 = k10, k12 = k12, k21 = k21)
out <- ode(y = c(A1 = D, A2 = 0), times = time, func = twocomp_ode, parms = parms)
ode_df <- data.frame(time = out[, "time"], conc_ode = out[, "A1"] / V1)

ggplot() +
  geom_line(data = df, aes(time, conc), linewidth = 1, color = "steelblue") +
  geom_point(data = ode_df[seq(1, nrow(ode_df), 10), ],
             aes(time, conc_ode), color = "red", size = 1.5) +
  scale_y_log10() +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Closed-Form vs deSolve Verification")

# ----------------------------------------------------------------------
# Section: Simulated data with NLS fit
# ----------------------------------------------------------------------
# Simulated observations and overlay of the true biexponential curve.
# (Biexponential NLS is notoriously ill-conditioned; we demonstrate
#  identification challenges rather than force an unstable fit.)
conc_true <- C_biexp(time, A_coef, B_coef, alpha, beta)
conc_obs <- conc_true * exp(rnorm(length(time), 0, 0.08))
idx <- seq(1, length(time), by = 3)
obs_df <- data.frame(
  time = time[idx],
  conc = conc_obs[idx],
  pred = conc_true[idx]
)

cat("True macroconstants:\n")
print(round(c(A = A_coef, B = B_coef, alpha = alpha, beta = beta), 4))

ggplot(obs_df, aes(time, conc)) +
  geom_point(size = 2, color = "steelblue") +
  geom_line(aes(y = pred), linewidth = 1, color = "red") +
  scale_y_log10() +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Noisy Data vs True Biexponential Curve")

# ----------------------------------------------------------------------
# Section: Phase stripping illustration
# ----------------------------------------------------------------------
# Feathering / phase stripping on the true curve (no noise)
strip_df <- data.frame(time = time, conc = C_biexp(time, A_coef, B_coef, alpha, beta))
term_df <- subset(strip_df, time >= 18)
term_fit <- lm(log(conc) ~ time, data = term_df)
beta_est <- -coef(term_fit)[2]
B_est <- exp(coef(term_fit)[1])

strip_df$residual <- pmax(strip_df$conc - B_est * exp(-beta_est * strip_df$time), 1e-8)
init_df <- subset(strip_df, time > 0.1 & time <= 2)
init_fit <- lm(log(residual) ~ time, data = init_df)
alpha_est <- -coef(init_fit)[2]

cat("Graphical estimates: alpha =", round(alpha_est, 4),
    ", beta =", round(beta_est, 4), "\n")
cat("True values:         alpha =", round(alpha, 4),
    ", beta =", round(beta, 4), "\n")

