# Three-Compartment Pharmacokinetic Models
# Extracted executable R code from 16-three-compartment-models.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Implementation
# ----------------------------------------------------------------------
library(ggplot2)
library(deSolve)
library(dplyr)
library(tidyr)

set.seed(20260731)

# --- Microconstants ---
k10 <- 0.05
k12 <- 0.60
k21 <- 0.40
k13 <- 0.15
k31 <- 0.08
V1  <- 8
D   <- 100

# --- ODE system ---
threecomp_ode <- function(t, state, parms) {
  with(as.list(c(state, parms)), {
    dA1 <- -(k10 + k12 + k13) * A1 + k21 * A2 + k31 * A3
    dA2 <- k12 * A1 - k21 * A2
    dA3 <- k13 * A1 - k31 * A3
    list(c(dA1, dA2, dA3))
  })
}

parms <- c(k10 = k10, k12 = k12, k21 = k21, k13 = k13, k31 = k31)
time <- seq(0, 72, 0.1)
out <- ode(y = c(A1 = D, A2 = 0, A3 = 0), times = time,
           func = threecomp_ode, parms = parms)

df <- data.frame(
  time = out[, "time"],
  conc = out[, "A1"] / V1,
  A1 = out[, "A1"],
  A2 = out[, "A2"],
  A3 = out[, "A3"]
)

Vss <- V1 * (1 + k12 / k21 + k13 / k31)
CL  <- k10 * V1

cat("V1:", V1, "L\n")
cat("Vss:", round(Vss, 1), "L\n")
cat("CL:", round(CL, 2), "L/h\n")

# ----------------------------------------------------------------------
# Section: Triexponential concentration profile
# ----------------------------------------------------------------------
ggplot(df, aes(time, conc)) +
  geom_line(linewidth = 1, color = "steelblue") +
  scale_y_log10() +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Three-Compartment IV Bolus (Semi-Log)")

# ----------------------------------------------------------------------
# Section: Compartment amounts over time
# ----------------------------------------------------------------------
df_long <- df %>%
  select(time, A1, A2, A3) %>%
  tidyr::pivot_longer(-time, names_to = "compartment", values_to = "amount")

ggplot(df_long, aes(time, amount, color = compartment)) +
  geom_line(linewidth = 1) +
  labs(x = "Time (h)", y = "Amount (mg)",
       title = "Drug Amount in Each Compartment") +
  scale_color_brewer(palette = "Set1")

# ----------------------------------------------------------------------
# Section: NLS fit of triexponential
# ----------------------------------------------------------------------
conc_true <- df$conc
conc_obs <- conc_true * exp(rnorm(nrow(df), 0, 0.06))
idx <- seq(1, nrow(df), by = 5)
obs_df <- data.frame(time = df$time[idx], conc = conc_obs[idx], pred = conc_true[idx])

ggplot(obs_df, aes(time, conc)) +
  geom_point(size = 2, color = "steelblue") +
  geom_line(aes(y = pred), linewidth = 1, color = "red") +
  scale_y_log10() +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Noisy Data vs Three-Compartment ODE Solution")

# ----------------------------------------------------------------------
# Section: Two vs three compartment comparison
# ----------------------------------------------------------------------
# Compare one- vs three-compartment descriptions via residual sum of squares
# One-compartment: monoexponential with rate CL/Vss (simplest single-rate summary)
k_app <- CL / Vss
pred1 <- (D / Vss) * exp(-k_app * obs_df$time)
pred3 <- obs_df$pred

rss1 <- sum((obs_df$conc - pred1)^2)
rss3 <- sum((obs_df$conc - pred3)^2)
n <- nrow(obs_df)
AIC1 <- n * log(rss1 / n) + 2 * 2
AIC3 <- n * log(rss3 / n) + 2 * 6

cat("\nAIC (1-comp approx):", round(AIC1, 1), "\n")
cat("AIC (3-comp ODE):", round(AIC3, 1), "\n")
cat("Delta AIC:", round(AIC1 - AIC3, 1), "\n")

