# Nonlinear Pharmacokinetics
# Extracted executable R code from 17-nonlinear-pharmacokinetics.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Implementation
# ----------------------------------------------------------------------
library(ggplot2)
library(deSolve)
library(dplyr)

set.seed(20260731)

# --- Michaelis-Menten parameters (phenytoin-like) ---
Vmax <- 350       # mg/h (~7 mg/kg/day for 70 kg)
Km   <- 8         # mg/L
Vd   <- 50        # L
D    <- 1000      # mg IV loading dose (~15 mg/kg), giving C0 = 20 mg/L

# C0 / Km = 2.5, so the profile starts in the saturated regime and decays
# through the transition into first-order elimination. Both regimes must be
# observed for Vmax and Km to be separately identifiable (see below).

# ----------------------------------------------------------------------
# Section: ODE definition and numerical solution
# ----------------------------------------------------------------------
mm_ode <- function(t, state, parms) {
  C <- state["C"]
  Vmax <- parms["Vmax"]
  Km <- parms["Km"]
  V <- parms["V"]
  dC <- -(Vmax / V) * C / (Km + C)
  list(c(dC))
}

times <- seq(0, 72, 0.05)
C0 <- D / Vd

out <- ode(y = c(C = C0), times = times, func = mm_ode,
           parms = c(Vmax = Vmax, Km = Km, V = Vd))

df <- data.frame(time = out[, "time"], conc = out[, "C"])

# ----------------------------------------------------------------------
# Section: Concentration-time profile
# ----------------------------------------------------------------------
ggplot(df, aes(time, conc)) +
  geom_line(linewidth = 1, color = "steelblue") +
  geom_hline(yintercept = Km, linetype = "dashed", color = "orange") +
  annotate("text", x = 60, y = Km + 1, label = paste("Km =", Km, "mg/L")) +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Nonlinear (Michaelis-Menten) Elimination")

# ----------------------------------------------------------------------
# Section: Dose nonlinearity: AUC vs dose
# ----------------------------------------------------------------------
doses <- c(100, 200, 300, 400, 500, 600)
auc_results <- sapply(doses, function(d) {
  C0 <- d / Vd
  out_d <- ode(y = c(C = C0), times = seq(0, 200, 0.1),
               func = mm_ode, parms = c(Vmax = Vmax, Km = Km, V = Vd))
  conc_d <- out_d[, "C"]
  time_d <- out_d[, "time"]
  sum(diff(time_d) * (conc_d[-1] + conc_d[-length(conc_d)]) / 2)
})

# Compare with linear kinetics: CL at low concentration is Vmax/Km (L/h)
CL_linear <- Vmax / Km
auc_linear <- doses / CL_linear

dose_df <- data.frame(
  dose = rep(doses, 2),
  AUC = c(auc_results, auc_linear),
  model = rep(c("Michaelis-Menten", "Linear"), each = length(doses))
)

ggplot(dose_df, aes(dose, AUC, color = model)) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  labs(x = "Dose (mg)", y = "AUC (mg·h/L)",
       title = "Dose-AUC Relationship: Nonlinear vs Linear") +
  scale_color_brewer(palette = "Set1")

# ----------------------------------------------------------------------
# Section: Apparent clearance vs concentration
# ----------------------------------------------------------------------
C_range <- seq(0.1, 40, 0.1)
CL_app <- Vmax / (Km + C_range)

cl_df <- data.frame(conc = C_range, CL_app = CL_app)

ggplot(cl_df, aes(conc, CL_app)) +
  geom_line(linewidth = 1, color = "steelblue") +
  geom_vline(xintercept = Km, linetype = "dashed", color = "orange") +
  labs(x = "Concentration (mg/L)", y = "Apparent CL (L/h)",
       title = "Capacity-Limited Clearance Decreases with Concentration")

# ----------------------------------------------------------------------
# Section: Multiple doses at different levels
# ----------------------------------------------------------------------
simulate_doses <- function(d) {
  C0 <- d / Vd
  ode(y = c(C = C0), times = times,
      func = mm_ode, parms = c(Vmax = Vmax, Km = Km, V = Vd))[, "C"]
}

dose_compare <- data.frame(
  time = rep(times, 3),
  conc = c(simulate_doses(200), simulate_doses(400), simulate_doses(600)),
  dose = factor(rep(c("200 mg", "400 mg", "600 mg"), each = length(times)))
)

ggplot(dose_compare, aes(time, conc, color = dose)) +
  geom_line(linewidth = 1) +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Nonlinear Kinetics: Effect of Dose on Profile") +
  scale_color_brewer(palette = "Set1")

# ----------------------------------------------------------------------
# Section: Simulated data with MM fit
# ----------------------------------------------------------------------
conc_true <- df$conc
conc_obs <- conc_true * exp(rnorm(nrow(df), 0, 0.08))
idx <- seq(1, nrow(df), by = 6)
obs_df <- data.frame(time = df$time[idx], conc = conc_obs[idx])

# Fit using deSolve inside objective
mm_pred <- function(params, times, D, Vd) {
  Vmax_est <- params[1]; Km_est <- params[2]
  out <- ode(y = c(C = D / Vd), times = times, func = mm_ode,
             parms = c(Vmax = Vmax_est, Km = Km_est, V = Vd))
  out[, "C"]
}

obj <- function(params) {
  pred <- mm_pred(params, obs_df$time, D, Vd)
  sum((obs_df$conc - pred)^2)
}

opt <- optim(c(300, 10), obj, method = "L-BFGS-B",
             lower = c(50, 0.1), upper = c(1000, 50))

cat("True Vmax:", Vmax, "Estimated:", round(opt$par[1], 1), "\n")
cat("True Km:", Km, "Estimated:", round(opt$par[2], 2), "\n")
cat("True CL at low C (Vmax/Km):", round(Vmax / Km, 1),
    "Estimated:", round(opt$par[1] / opt$par[2], 1), "\n")

obs_df$pred <- mm_pred(opt$par, obs_df$time, D, Vd)

ggplot(obs_df, aes(time, conc)) +
  geom_point(size = 2, color = "steelblue") +
  geom_line(aes(y = pred), linewidth = 1, color = "red") +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Fitting Michaelis-Menten Model to Simulated Data")

