# Physiologically Based Pharmacokinetic Models
# Extracted executable R code from 18-pbpk.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Implementation
# ----------------------------------------------------------------------
library(deSolve)
library(ggplot2)
library(dplyr)
library(tidyr)

set.seed(20260731)

# --- Physiological parameters ---
V_b <- 5          # L blood volume

tissues <- data.frame(
  name = c("liver", "kidney", "muscle", "fat"),
  V    = c(1.8, 0.3, 30.0, 10.0),
  Q    = c(90, 60, 60, 15),
  Kp   = c(2.0, 1.5, 0.8, 5.0)
)

Q_total <- sum(tissues$Q)  # 225 L/h; modeled tissues only
CL_int  <- 15              # L/h intrinsic hepatic clearance
D       <- 100             # mg IV bolus

# ----------------------------------------------------------------------
# Section: PBPK ODE system
# ----------------------------------------------------------------------
pbpk_ode <- function(t, state, parms) {
  Ca <- state["Ca"]
  Ct_liver  <- state["Ct_liver"]
  Ct_kidney <- state["Ct_kidney"]
  Ct_muscle <- state["Ct_muscle"]
  Ct_fat    <- state["Ct_fat"]

  Kp <- parms$Kp; Q <- parms$Q; V <- parms$V

  # Tissue ODEs (liver includes intrinsic hepatic clearance)
  dCt_liver  <- Q[1] / V[1] * (Ca - Ct_liver / Kp[1]) -
                CL_int * (Ct_liver / Kp[1]) / V[1]
  dCt_kidney <- Q[2] / V[2] * (Ca - Ct_kidney / Kp[2])
  dCt_muscle <- Q[3] / V[3] * (Ca - Ct_muscle / Kp[3])
  dCt_fat    <- Q[4] / V[4] * (Ca - Ct_fat / Kp[4])

  # Venous contributions
  Cv_sum <- Q[1] * Ct_liver / Kp[1] +
            Q[2] * Ct_kidney / Kp[2] +
            Q[3] * Ct_muscle / Kp[3] +
            Q[4] * Ct_fat / Kp[4]

  # Blood ODE (mass-balanced flows; elimination is in liver)
  dCa <- (Cv_sum - Q_total * Ca) / V_b

  list(c(dCa, dCt_liver, dCt_kidney, dCt_muscle, dCt_fat))
}

init <- c(Ca = D / V_b, Ct_liver = 0, Ct_kidney = 0,
          Ct_muscle = 0, Ct_fat = 0)
parms <- list(V = tissues$V, Q = tissues$Q, Kp = tissues$Kp)

times <- seq(0, 48, 0.05)
out <- ode(y = init, times = times, func = pbpk_ode, parms = parms)

# ----------------------------------------------------------------------
# Section: Plasma concentration-time profile
# ----------------------------------------------------------------------
plasma_df <- data.frame(time = out[, "time"], Ca = out[, "Ca"])

ggplot(plasma_df, aes(time, Ca)) +
  geom_line(linewidth = 1, color = "steelblue") +
  scale_y_log10() +
  labs(x = "Time (h)", y = "Plasma concentration (mg/L)",
       title = "PBPK Model: Plasma Concentration After IV Bolus")

# ----------------------------------------------------------------------
# Section: Tissue concentrations
# ----------------------------------------------------------------------
tissue_df <- data.frame(
  time = out[, "time"],
  liver  = out[, "Ct_liver"],
  kidney = out[, "Ct_kidney"],
  muscle = out[, "Ct_muscle"],
  fat    = out[, "Ct_fat"]
) %>%
  pivot_longer(-time, names_to = "tissue", values_to = "concentration")

ggplot(tissue_df, aes(time, concentration, color = tissue)) +
  geom_line(linewidth = 1) +
  labs(x = "Time (h)", y = "Tissue concentration (mg/L)",
       title = "PBPK Model: Tissue Concentrations") +
  scale_color_brewer(palette = "Set1")

# ----------------------------------------------------------------------
# Section: Tissue vs plasma at steady state
# ----------------------------------------------------------------------
# Drive to true steady state with constant IV infusion
R_inf <- 10  # mg/h

pbpk_inf_ode <- function(t, state, parms) {
  Ca <- state["Ca"]
  Ct_liver  <- state["Ct_liver"]
  Ct_kidney <- state["Ct_kidney"]
  Ct_muscle <- state["Ct_muscle"]
  Ct_fat    <- state["Ct_fat"]

  Kp <- parms$Kp; Q <- parms$Q; V <- parms$V

  dCt_liver  <- Q[1] / V[1] * (Ca - Ct_liver / Kp[1]) -
                CL_int * (Ct_liver / Kp[1]) / V[1]
  dCt_kidney <- Q[2] / V[2] * (Ca - Ct_kidney / Kp[2])
  dCt_muscle <- Q[3] / V[3] * (Ca - Ct_muscle / Kp[3])
  dCt_fat    <- Q[4] / V[4] * (Ca - Ct_fat / Kp[4])

  Cv_sum <- Q[1] * Ct_liver / Kp[1] +
            Q[2] * Ct_kidney / Kp[2] +
            Q[3] * Ct_muscle / Kp[3] +
            Q[4] * Ct_fat / Kp[4]

  dCa <- (Cv_sum - Q_total * Ca + R_inf) / V_b

  list(c(dCa, dCt_liver, dCt_kidney, dCt_muscle, dCt_fat))
}

init_inf <- c(Ca = 0, Ct_liver = 0, Ct_kidney = 0,
              Ct_muscle = 0, Ct_fat = 0)
times_inf <- seq(0, 100, 0.1)
out_inf <- ode(y = init_inf, times = times_inf,
               func = pbpk_inf_ode, parms = parms)

ss <- out_inf[nrow(out_inf), ]
ss_ratios <- c(
  ss["Ct_liver"] / ss["Ca"],
  ss["Ct_kidney"] / ss["Ca"],
  ss["Ct_muscle"] / ss["Ca"],
  ss["Ct_fat"] / ss["Ca"]
)

# Non-eliminating tissues: Kp_obs -> Kp.
# Liver: Kp_obs -> Kp * Q_liver / (Q_liver + CL_int) under well-stirred elimination.
Kp_pred_ss <- tissues$Kp
Kp_pred_ss[1] <- tissues$Kp[1] * tissues$Q[1] / (tissues$Q[1] + CL_int)

ratio_df <- data.frame(
  tissue = tissues$name,
  Kp_pred = Kp_pred_ss,
  Kp_obs = as.numeric(ss_ratios)
)

cat("Steady-state tissue/plasma ratios (constant IV infusion):\n")
print(ratio_df)

# ----------------------------------------------------------------------
# Section: Effect of clearance on plasma profile
# ----------------------------------------------------------------------
CL_values <- c(5, 15, 30)
cl_results <- lapply(CL_values, function(cl_val) {
  pbpk_ode_cl <- function(t, state, parms) {
    Ca <- state["Ca"]
    Ct <- state[2:5]
    Kp <- parms$Kp; Q <- parms$Q; V <- parms$V
    Q_tot <- sum(Q)
    dCt <- Q / V * (Ca - Ct / Kp)
    # Intrinsic clearance acts on liver venous concentration (tissue 1)
    dCt[1] <- dCt[1] - cl_val * (Ct[1] / Kp[1]) / V[1]
    Cv_sum <- sum(Q * Ct / Kp)
    dCa <- (Cv_sum - Q_tot * Ca) / V_b
    list(c(dCa, dCt))
  }
  out_cl <- ode(y = init, times = times, func = pbpk_ode_cl, parms = parms)
  data.frame(time = out_cl[, "time"], Ca = out_cl[, "Ca"],
             CL = paste0("CL_int = ", cl_val, " L/h"))
})

cl_df <- bind_rows(cl_results)

ggplot(cl_df, aes(time, Ca, color = CL)) +
  geom_line(linewidth = 1) +
  scale_y_log10() +
  labs(x = "Time (h)", y = "Plasma concentration (mg/L)",
       title = "PBPK: Effect of Intrinsic Hepatic Clearance") +
  scale_color_brewer(palette = "Set1")

