# Noncompartmental Analysis: Principles
# Extracted executable R code from 19-nca-principles.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Example: Moments from Simulated Data {#sec-nca-moments-sim}
# ----------------------------------------------------------------------
set.seed(20260731)
library(ggplot2)
library(dplyr)

# One-compartment IV bolus parameters
D <- 100   # mg
V <- 20    # L
k <- 0.15  # h^-1
CL <- k * V

time <- seq(0, 24, by = 0.5)
conc <- (D / V) * exp(-k * time)

pk <- data.frame(TIME = time, CONC = conc)

# Linear trapezoidal AUC
dt <- diff(pk$TIME)
avg_conc <- (pk$CONC[-1] + pk$CONC[-length(pk$CONC)]) / 2
AUC <- sum(avg_conc * dt)

# AUMC: linear trapezoid of t * C(t)
AUMC <- sum(
  (pk$TIME[-1] * pk$CONC[-1] +
     pk$TIME[-length(pk$TIME)] * pk$CONC[-length(pk$CONC)]) / 2 * dt
)

# Extrapolate moments to infinity (known terminal slope k)
C_last <- tail(pk$CONC, 1)
t_last <- tail(pk$TIME, 1)
AUC_inf <- AUC + C_last / k
AUMC_inf <- AUMC + t_last * C_last / k + C_last / k^2

MRT <- AUMC_inf / AUC_inf
Vss <- CL * MRT

data.frame(
  AUC_0t = AUC,
  AUC_inf = AUC_inf,
  AUMC_inf = AUMC_inf,
  MRT = MRT,
  CL = CL,
  Vss = Vss,
  Vss_true = V
)

# ----------------------------------------------------------------------
# Section: R Example: Moments from Simulated Data {#sec-nca-moments-sim}
# ----------------------------------------------------------------------
ggplot(pk, aes(TIME, CONC)) +
  geom_line(linewidth = 0.8) +
  geom_ribbon(aes(ymax = CONC, ymin = 0), alpha = 0.2, fill = "steelblue") +
  labs(
    x = "Time (h)",
    y = "Concentration (mg/L)",
    title = "AUC as the zeroth moment of C(t)"
  ) +
  theme_bw()

# ----------------------------------------------------------------------
# Section: R Example: Observed IV Bolus Data
# ----------------------------------------------------------------------
library(readr)

pk_iv <- read_csv("data/pk_iv_bolus.csv", show_col_types = FALSE)

# Linear trapezoidal AUC and AUMC for subject 101
subj <- pk_iv %>%
  filter(USUBJID == "101") %>%
  arrange(TIME)

dt <- diff(subj$TIME)
avg <- (subj$CONC[-1] + subj$CONC[-nrow(subj)]) / 2
AUC_obs <- sum(avg * dt)

# Linear trapezoid of t * C(t)
AUMC_obs <- sum(
  (subj$TIME[-1] * subj$CONC[-1] +
     subj$TIME[-nrow(subj)] * subj$CONC[-nrow(subj)]) / 2 * dt
)

MRT_obs <- AUMC_obs / AUC_obs
D <- unique(subj$DOSE)
CL_obs <- D / AUC_obs
Vss_obs <- CL_obs * MRT_obs

data.frame(
  AUC_0t = round(AUC_obs, 2),
  AUMC_0t = round(AUMC_obs, 2),
  MRT = round(MRT_obs, 2),
  CL = round(CL_obs, 2),
  Vss = round(Vss_obs, 2)
)

