# Noncompartmental Analysis: Implementation in R
# Extracted executable R code from 20-nca-implementation.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Manual R Functions
# ----------------------------------------------------------------------
set.seed(20260731)
library(dplyr)
library(ggplot2)
library(readr)

# Linear trapezoidal AUC
auc_linear <- function(time, conc) {
  ok <- !is.na(conc) & conc >= 0
  time <- time[ok]
  conc <- conc[ok]
  if (length(time) < 2) return(NA_real_)
  dt <- diff(time)
  avg <- (conc[-1] + conc[-length(conc)]) / 2
  sum(avg * dt)
}

# Lin-up / log-down trapezoidal AUC
auc_lin_up_log_down <- function(time, conc) {
  ok <- !is.na(conc) & conc > 0
  time <- time[ok]
  conc <- conc[ok]
  if (length(time) < 2) return(NA_real_)
  total <- 0
  for (i in seq_len(length(time) - 1)) {
    c1 <- conc[i]
    c2 <- conc[i + 1]
    dt <- time[i + 1] - time[i]
    if (c1 > c2 && c2 > 0) {
      total <- total + (c1 - c2) / log(c1 / c2) * dt
    } else {
      total <- total + (c1 + c2) / 2 * dt
    }
  }
  total
}

# Terminal lambda_z from last n points
est_lambda_z <- function(time, conc, n = 3) {
  ok <- !is.na(conc) & conc > 0
  time <- time[ok]
  conc <- conc[ok]
  n <- min(n, length(time))
  idx <- (length(time) - n + 1):length(time)
  fit <- lm(log(conc[idx]) ~ time[idx])
  -coef(fit)[["time[idx]"]]
}

# ----------------------------------------------------------------------
# Section: Apply Manual Functions to IV Bolus Data
# ----------------------------------------------------------------------
pk_iv <- read_csv("data/pk_iv_bolus.csv", show_col_types = FALSE)

subj <- pk_iv %>%
  filter(USUBJID == "101") %>%
  arrange(TIME)

AUC_lin <- auc_linear(subj$TIME, subj$CONC)
AUC_log <- auc_lin_up_log_down(subj$TIME, subj$CONC)
lz <- est_lambda_z(subj$TIME, subj$CONC, n = 3)
C_last <- tail(subj$CONC, 1)
AUC_inf <- AUC_lin + C_last / lz
CL <- unique(subj$DOSE) / AUC_inf
t_half <- log(2) / lz

data.frame(
  AUC_linear = round(AUC_lin, 2),
  AUC_lin_up_log_down = round(AUC_log, 2),
  lambda_z = round(lz, 4),
  t_half = round(t_half, 2),
  AUC_inf = round(AUC_inf, 2),
  CL = round(CL, 2)
)

# ----------------------------------------------------------------------
# Section: Visualize Trapezoidal Areas
# ----------------------------------------------------------------------
subj_plot <- subj %>%
  mutate(
    seg = paste0(TIME, "–", lead(TIME)),
    mid = (TIME + lead(TIME)) / 2,
    trap = (CONC + lead(CONC)) / 2 * (lead(TIME) - TIME)
  ) %>%
  filter(!is.na(trap))

ggplot(subj, aes(TIME, CONC)) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 2) +
  geom_segment(
    data = subj_plot,
    aes(x = TIME, xend = lead(TIME), y = CONC, yend = lead(CONC)),
    linetype = "dashed", alpha = 0.5
  ) +
  labs(
    x = "Time (h)", y = "Concentration (mg/L)",
    title = "Linear trapezoidal decomposition (subject 101)"
  ) +
  theme_bw()

# ----------------------------------------------------------------------
# Section: PKNCA Workflow
# ----------------------------------------------------------------------
library(PKNCA)

pk_iv <- read_csv("data/pk_iv_bolus.csv", show_col_types = FALSE)

dose_df <- pk_iv %>%
  filter(TIME == 0) %>%
  mutate(route_pk = "intravascular")

conc_obj <- PKNCAconc(pk_iv, formula = CONC ~ TIME | USUBJID)
dose_obj <- PKNCAdose(
  dose_df,
  formula = DOSE ~ TIME | USUBJID,
  route = "route_pk"
)
data_obj <- PKNCAdata(conc_obj, dose_obj)
# Request CL and MRT (not enabled in PKNCA default intervals)
data_obj$intervals$cl.obs <- data_obj$intervals$end == Inf
data_obj$intervals$aumclast <- data_obj$intervals$end != Inf
data_obj$intervals$mrt.last <- data_obj$intervals$end != Inf
data_obj$intervals$mrt.obs <- data_obj$intervals$end == Inf
data_obj$intervals$vss.obs <- data_obj$intervals$end == Inf
nca_res <- pk.nca(data_obj)

nca_tbl <- as.data.frame(nca_res$result)
nca_tbl %>%
  filter(PPTESTCD %in% c(
    "auclast", "aucinf.obs", "cmax", "tmax", "half.life",
    "lambda.z", "cl.obs", "mrt.last", "mrt.obs", "vss.obs"
  )) %>%
  select(PPTESTCD, PPORRES)

# ----------------------------------------------------------------------
# Section: PKNCA Options
# ----------------------------------------------------------------------
# View default options
PKNCA.options("auc.method")
PKNCA.options("min.hl.r.squared")

# ----------------------------------------------------------------------
# Section: PKNCA Options
# ----------------------------------------------------------------------
# Compare default lin-up/log-down with pure linear integration
PKNCA.options(auc.method = "linear")
nca_res2 <- pk.nca(data_obj)
as.data.frame(nca_res2$result) %>%
  filter(PPTESTCD == "aucinf.obs") %>%
  select(PPTESTCD, PPORRES)
# Restore the chapter default
PKNCA.options(auc.method = "lin up/log down")

# ----------------------------------------------------------------------
# Section: Compare Manual and PKNCA Results
# ----------------------------------------------------------------------
pknca_auc <- nca_res$result %>%
  as.data.frame() %>%
  filter(PPTESTCD == "aucinf.obs") %>%
  pull(PPORRES)

pknca_cl <- nca_res$result %>%
  as.data.frame() %>%
  filter(PPTESTCD == "cl.obs") %>%
  pull(PPORRES)
stopifnot(length(pknca_cl) == 1)

data.frame(
  method = c("Manual (linear + extrap)", "PKNCA"),
  AUC_inf = c(round(AUC_inf, 2), round(pknca_auc, 2)),
  CL = c(round(CL, 2), round(pknca_cl, 2))
)

# ----------------------------------------------------------------------
# Section: BLQ Handling
# ----------------------------------------------------------------------
# Illustration: BLQ flag
pk_blq <- pk_iv %>%
  mutate(
    LLOQ = 0.2,
    BLQ = CONC < LLOQ,
    CONC_nca = if_else(BLQ, 0, CONC)
  )

pk_blq %>%
  select(TIME, CONC, BLQ, CONC_nca)

# ----------------------------------------------------------------------
# Section: AUMC and MRT in R
# ----------------------------------------------------------------------
aumc_linear <- function(time, conc) {
  ok <- !is.na(conc) & conc >= 0
  time <- time[ok]
  conc <- conc[ok]
  if (length(time) < 2) return(NA_real_)
  dt <- diff(time)
  # Linear trapezoid of t * C(t), not (t_mid)*(C_mid)
  sum((time[-1] * conc[-1] + time[-length(time)] * conc[-length(conc)]) / 2 * dt)
}

AUMC_0t <- aumc_linear(subj$TIME, subj$CONC)
MRT_0t <- AUMC_0t / AUC_lin

# Extrapolated AUMC contribution
t_last <- tail(subj$TIME, 1)
C_last <- tail(subj$CONC, 1)
AUMC_extra <- t_last * C_last / lz + C_last / lz^2
AUMC_inf <- AUMC_0t + AUMC_extra
MRT_inf <- AUMC_inf / AUC_inf
Vss <- CL * MRT_inf

data.frame(
  AUMC_0t = round(AUMC_0t, 2),
  AUMC_extra = round(AUMC_extra, 2),
  MRT_0t = round(MRT_0t, 2),
  MRT_inf = round(MRT_inf, 2),
  Vss = round(Vss, 2)
)

# ----------------------------------------------------------------------
# Section: Quality Checks
# ----------------------------------------------------------------------
pct_extra <- 100 * (AUC_inf - AUC_lin) / AUC_inf
cat("Percent extrapolated:", round(pct_extra, 1), "%\n")

