# Regulatory Noncompartmental Analysis
# Extracted executable R code from 21-regulatory-nca.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Summary Tables Mindset
# ----------------------------------------------------------------------
set.seed(20260731)
library(dplyr)
library(readr)
library(tidyr)

pk_oral <- read_csv("data/pk_oral_multi.csv", show_col_types = FALSE)

# Subject-level NCA-like summaries (simplified)
summarize_pk <- function(df) {
  df <- df %>% arrange(TIME)
  dt <- diff(df$TIME)
  avg <- (df$CONC[-1] + df$CONC[-nrow(df)]) / 2
  auc <- sum(avg * dt, na.rm = TRUE)
  tibble(
    Cmax = max(df$CONC, na.rm = TRUE),
    Tmax = df$TIME[which.max(df$CONC)],
    AUC0t = auc
  )
}

pk_params <- pk_oral %>%
  group_by(USUBJID) %>%
  group_modify(~ summarize_pk(.x)) %>%
  ungroup()

pk_params %>%
  summarise(
    N = n(),
    Cmax_mean = mean(Cmax),
    Cmax_cv = 100 * sd(Cmax) / mean(Cmax),
    AUC_mean = mean(AUC0t),
    AUC_cv = 100 * sd(AUC0t) / mean(AUC0t)
  )

# ----------------------------------------------------------------------
# Section: Subject Listings Mindset
# ----------------------------------------------------------------------
pk_params %>%
  mutate(
    Cmax = round(Cmax, 3),
    AUC0t = round(AUC0t, 2)
  ) %>%
  head(10) %>%
  knitr::kable(caption = "Subject listing (first 10 subjects)")

# ----------------------------------------------------------------------
# Section: R Example: Regulatory-Style Summary Table
# ----------------------------------------------------------------------
library(PKNCA)

# NCA on oral multi-subject data (simplified regulatory table)
dose_oral <- pk_oral %>%
  filter(TIME == 0) %>%
  mutate(route_pk = "extravascular")

conc_o <- PKNCAconc(pk_oral, formula = CONC ~ TIME | USUBJID)
dose_o <- PKNCAdose(
  dose_oral,
  formula = DOSE ~ TIME | USUBJID,
  route = "route_pk"
)

# Request clearance; for extravascular dosing PKNCA's cl.obs is CL/F
intervals_o <- data.frame(
  start = 0,
  end = Inf,
  cmax = TRUE,
  tmax = TRUE,
  auclast = TRUE,
  half.life = TRUE,
  cl.obs = TRUE
)
data_o <- PKNCAdata(conc_o, dose_o, intervals = intervals_o)
res_o <- pk.nca(data_o)

# Wide format subject parameters (cl.obs labeled CL/F for oral data)
params_wide <- res_o$result %>%
  as.data.frame() %>%
  select(USUBJID, PPTESTCD, PPORRES) %>%
  filter(PPTESTCD %in% c("cmax", "tmax", "auclast", "half.life", "cl.obs")) %>%
  pivot_wider(names_from = PPTESTCD, values_from = PPORRES) %>%
  rename(`CL/F` = cl.obs)

# Summary statistics for CSR Table 14.1-style output
params_wide %>%
  summarise(
    N = n(),
    Cmax_n = sum(!is.na(cmax)),
    Cmax_mean = mean(cmax, na.rm = TRUE),
    Cmax_sd = sd(cmax, na.rm = TRUE),
    Cmax_gmean = exp(mean(log(cmax), na.rm = TRUE)),
    AUC_n = sum(!is.na(auclast)),
    AUC_mean = mean(auclast, na.rm = TRUE),
    AUC_gmean = exp(mean(log(auclast), na.rm = TRUE))
  ) %>%
  mutate(across(where(is.numeric), ~ round(.x, 3)))

# ----------------------------------------------------------------------
# Section: Figures for Regulatory Reports
# ----------------------------------------------------------------------
library(ggplot2)

mean_profile <- pk_oral %>%
  group_by(TIME) %>%
  summarise(
    mean_conc = mean(CONC),
    sd_conc = sd(CONC),
    .groups = "drop"
  )

ggplot(mean_profile, aes(TIME, mean_conc)) +
  geom_line(linewidth = 0.8) +
  geom_ribbon(
    aes(ymax = mean_conc + sd_conc, ymin = pmax(mean_conc - sd_conc, 0)),
    alpha = 0.2, fill = "steelblue"
  ) +
  labs(
    x = "Time (h)", y = "Concentration (mg/L)",
    title = "Mean (+ SD) concentration–time profile"
  ) +
  theme_bw()

ggplot(pk_oral, aes(TIME, CONC, group = USUBJID)) +
  geom_line(alpha = 0.4) +
  scale_y_log10() +
  labs(
    x = "Time (h)", y = "Concentration (mg/L, log scale)",
    title = "Individual profiles (semi-log)"
  ) +
  theme_bw()

