# Bioavailability
# Extracted executable R code from 22-bioavailability.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Example: Simulated IV vs Oral
# ----------------------------------------------------------------------
set.seed(20260731)
library(ggplot2)
library(dplyr)

# True parameters
D <- 100
CL <- 3.0
V <- 20
k <- CL / V
ka <- 0.8
F_true <- 0.65

time <- seq(0, 24, by = 0.25)

# IV bolus
C_iv <- (D / V) * exp(-k * time)

# Oral (one-compartment absorption)
C_po <- (F_true * D * ka / (V * (ka - k))) *
  (exp(-k * time) - exp(-ka * time))
C_po <- pmax(C_po, 0)

# AUC by trapezoidal rule
auc_fn <- function(t, c) {
  sum((c[-1] + c[-length(c)]) / 2 * diff(t))
}

AUC_iv <- auc_fn(time, C_iv)
AUC_po <- auc_fn(time, C_po)
F_est <- (AUC_po / AUC_iv) * (D / D)

data.frame(
  AUC_iv = round(AUC_iv, 2),
  AUC_po = round(AUC_po, 2),
  F_true = F_true,
  F_estimated = round(F_est, 3)
)

# ----------------------------------------------------------------------
# Section: R Example: Exposure Comparison Plot
# ----------------------------------------------------------------------
pk_compare <- bind_rows(
  data.frame(TIME = time, CONC = C_iv, ROUTE = "IV"),
  data.frame(TIME = time, CONC = C_po, ROUTE = "Oral")
)

ggplot(pk_compare, aes(TIME, CONC, color = ROUTE)) +
  geom_line(linewidth = 0.9) +
  labs(
    x = "Time (h)", y = "Concentration (mg/L)",
    title = "IV vs oral exposure (F = 0.65)"
  ) +
  theme_bw() +
  theme(legend.position = "bottom")

ggplot(pk_compare, aes(TIME, CONC, color = ROUTE)) +
  geom_line(linewidth = 0.9) +
  scale_y_log10() +
  labs(
    x = "Time (h)", y = "Concentration (mg/L, log)",
    title = "Semi-log view"
  ) +
  theme_bw() +
  theme(legend.position = "bottom")

# ----------------------------------------------------------------------
# Section: R Example: Book Datasets
# ----------------------------------------------------------------------
library(readr)
library(PKNCA)

pk_iv <- read_csv("data/pk_iv_bolus.csv", show_col_types = FALSE)
pk_oral <- read_csv("data/pk_oral_multi.csv", show_col_types = FALSE)

# IV NCA
dose_iv <- pk_iv %>% filter(TIME == 0) %>% mutate(route_pk = "intravascular")
conc_iv <- PKNCAconc(pk_iv, formula = CONC ~ TIME | USUBJID)
dose_iv_obj <- PKNCAdose(dose_iv, formula = DOSE ~ TIME | USUBJID, route = "route_pk")
res_iv <- pk.nca(PKNCAdata(conc_iv, dose_iv_obj))

AUC_iv <- res_iv$result %>%
  as.data.frame() %>%
  filter(PPTESTCD == "auclast") %>%
  pull(PPORRES)

# Oral NCA (mean AUC across subjects)
dose_oral <- pk_oral %>% filter(TIME == 0) %>% mutate(route_pk = "extravascular")
conc_oral <- PKNCAconc(pk_oral, formula = CONC ~ TIME | USUBJID)
dose_oral_obj <- PKNCAdose(dose_oral, formula = DOSE ~ TIME | USUBJID, route = "route_pk")
res_oral <- pk.nca(PKNCAdata(conc_oral, dose_oral_obj))

AUC_oral <- res_oral$result %>%
  as.data.frame() %>%
  filter(PPTESTCD == "auclast") %>%
  group_by(USUBJID) %>%
  summarise(AUC = PPORRES, .groups = "drop")

# Hypothetical absolute F if same drug, same dose
D_iv <- unique(pk_iv$DOSE)
D_po <- unique(pk_oral$DOSE)

F_hypothetical <- mean(AUC_oral$AUC) / AUC_iv * (D_iv / D_po)

data.frame(
  AUC_iv = round(AUC_iv, 2),
  AUC_oral_mean = round(mean(AUC_oral$AUC), 2),
  dose_iv = D_iv,
  dose_oral = D_po,
  F_if_same_drug = round(F_hypothetical, 3)
)

