# Bioequivalence
# Extracted executable R code from 23-bioequivalence.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Simulation: Crossover Data {#sec-be-simulation}
# ----------------------------------------------------------------------
set.seed(20260731)
library(dplyr)
library(tidyr)
library(ggplot2)

n_subj <- 24
# True GMR = 1.0 (bioequivalent)
mu_log_auc <- log(100)
sigma_between <- 0.25
sigma_within <- 0.15

subjects <- tibble(
  USUBJID = sprintf("%03d", 1:n_subj),
  SEQ = rep(c("TR", "RT"), each = n_subj / 2)
)

# The formulation effect is added only to the period that receives Test:
# period 1 for the TR sequence, period 2 for the RT sequence.
log_effect <- log(1.0)  # true GMR = 1.0, so the effect is zero here

be_data <- subjects %>%
  rowwise() %>%
  mutate(
    subj_eff = rnorm(1, 0, sigma_between),
    lnAUC_p1 = mu_log_auc + subj_eff + rnorm(1, 0, sigma_within) +
      if_else(SEQ == "TR", log_effect, 0),
    lnAUC_p2 = mu_log_auc + subj_eff + rnorm(1, 0, sigma_within) +
      if_else(SEQ == "TR", 0, log_effect)
  ) %>%
  ungroup()

# Reshape to long format with correct treatment assignment
be_long <- be_data %>%
  select(USUBJID, SEQ, lnAUC_p1, lnAUC_p2) %>%
  pivot_longer(
    cols = c(lnAUC_p1, lnAUC_p2),
    names_to = "period",
    values_to = "lnAUC"
  ) %>%
  mutate(
    PERIOD = if_else(period == "lnAUC_p1", 1L, 2L),
    TRT = case_when(
      SEQ == "TR" & PERIOD == 1 ~ "Test",
      SEQ == "TR" & PERIOD == 2 ~ "Reference",
      SEQ == "RT" & PERIOD == 1 ~ "Reference",
      SEQ == "RT" & PERIOD == 2 ~ "Test"
    ),
    AUC = exp(lnAUC)
  )

be_long %>%
  group_by(TRT) %>%
  summarise(
    N = n(),
    AUC_gmean = exp(mean(lnAUC)),
    .groups = "drop"
  )

# ----------------------------------------------------------------------
# Section: R: TOST Analysis
# ----------------------------------------------------------------------
# Simplified TOST for ln(AUC): Test vs Reference
test_vals <- be_long %>% filter(TRT == "Test") %>% pull(lnAUC)
ref_vals <- be_long %>% filter(TRT == "Reference") %>% pull(lnAUC)

# Paired analysis (crossover): match by subject.
# PERIOD must be dropped before pivoting: keeping it would make every
# (subject, period) cell unique, yielding 48 half-empty rows instead of 24 pairs.
paired <- be_long %>%
  select(USUBJID, TRT, lnAUC) %>%
  pivot_wider(names_from = TRT, values_from = lnAUC)

diff_log <- paired$Test - paired$Reference
n <- length(diff_log)
mean_diff <- mean(diff_log)
se_diff <- sd(diff_log) / sqrt(n)

# 90% CI for GMR (equivalent to TOST at alpha = 0.05)
t_crit <- qt(0.95, df = n - 1)
ci_low <- exp(mean_diff - t_crit * se_diff)
ci_high <- exp(mean_diff + t_crit * se_diff)
gmr <- exp(mean_diff)

# TOST p-values
t_stat_L <- (mean_diff - log(0.80)) / se_diff
t_stat_U <- (mean_diff - log(1.25)) / se_diff
p_TOST_L <- 1 - pt(t_stat_L, df = n - 1)
p_TOST_U <- pt(t_stat_U, df = n - 1)
p_TOST <- max(p_TOST_L, p_TOST_U)

data.frame(
  GMR = round(gmr, 4),
  CI_90_low = round(ci_low, 4),
  CI_90_high = round(ci_high, 4),
  BE_conclusion = if_else(ci_low >= 0.80 & ci_high <= 1.25, "BE demonstrated", "BE NOT demonstrated"),
  p_TOST = round(p_TOST, 4)
)

# ----------------------------------------------------------------------
# Section: Visualize Simulated BE Data
# ----------------------------------------------------------------------
ggplot(be_long, aes(PERIOD, AUC, group = USUBJID, color = TRT)) +
  geom_line(alpha = 0.4) +
  geom_point(size = 2) +
  scale_y_log10() +
  labs(
    x = "Period", y = "AUC (log scale)",
    title = "Individual AUC by period (crossover)"
  ) +
  theme_bw()

# Forest-style GMR plot
forest_df <- data.frame(
  param = "AUC",
  GMR = gmr,
  low = ci_low,
  high = ci_high
)

ggplot(forest_df, aes(x = GMR, y = param)) +
  geom_vline(xintercept = c(0.80, 1.00, 1.25), linetype = c("dashed", "solid", "dashed")) +
  geom_errorbarh(aes(xmin = low, xmax = high), height = 0.1, linewidth = 0.8) +
  geom_point(size = 3) +
  scale_x_continuous(limits = c(0.7, 1.3)) +
  labs(x = "Geometric Mean Ratio (Test/Reference)", title = "90% CI for AUC") +
  theme_bw()

# ----------------------------------------------------------------------
# Section: Simulate a Bio-Inequivalent Product
# ----------------------------------------------------------------------
set.seed(20260731)
true_gmr <- 1.15          # 15% higher exposure
sigma_within_hv <- 0.45   # highly variable drug, CV = sqrt(exp(s^2)-1) ~ 47%

# Test and reference must each get their OWN residual draw. Reusing a single
# draw would make every subject's difference identical and the CI zero-width.
be_bad <- subjects %>%
  rowwise() %>%
  mutate(
    subj_eff   = rnorm(1, 0, sigma_between),
    lnAUC_ref  = mu_log_auc + subj_eff + rnorm(1, 0, sigma_within_hv),
    lnAUC_test = mu_log_auc + subj_eff + log(true_gmr) +
                 rnorm(1, 0, sigma_within_hv)
  ) %>%
  ungroup()

diff_bad <- be_bad$lnAUC_test - be_bad$lnAUC_ref
n_bad <- length(diff_bad)
mean_bad <- mean(diff_bad)
se_bad <- sd(diff_bad) / sqrt(n_bad)
t_crit_bad <- qt(0.95, df = n_bad - 1)
ci_low_bad <- exp(mean_bad - t_crit_bad * se_bad)
ci_high_bad <- exp(mean_bad + t_crit_bad * se_bad)

data.frame(
  true_GMR = true_gmr,
  observed_GMR = round(exp(mean_bad), 3),
  CI_90 = paste0("[", round(ci_low_bad, 3), ", ", round(ci_high_bad, 3), "]"),
  BE = if_else(ci_low_bad >= 0.80 & ci_high_bad <= 1.25, "Pass", "Fail")
)

