# Food Effect Studies
# Extracted executable R code from 24-food-effect.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Simulation: Fasted vs Fed Profiles
# ----------------------------------------------------------------------
set.seed(20260731)
library(ggplot2)
library(dplyr)

# Shared elimination parameters
D <- 100
V <- 30
k <- 0.12
CL <- k * V

# Bateman function. Fbio (not F) because F is base R's FALSE.
# At ka == k the Bateman form is 0/0; the limit is Fbio*D*k/V * t * exp(-k*t),
# which is what we return rather than a misleading vector of zeros.
bateman <- function(t, D, V, ka, k, Fbio = 1) {
  if (abs(ka - k) < 1e-8) return(Fbio * D * k / V * t * exp(-k * t))
  Fbio * D * ka / (V * (ka - k)) * (exp(-k * t) - exp(-ka * t))
}

time <- seq(0, 24, by = 0.1)

# Fasted: fast absorption, incomplete bioavailability
ka_fasted <- 1.0
F_fasted  <- 0.65
C_fasted <- pmax(bateman(time, D, V, ka_fasted, k, Fbio = F_fasted), 0)

# Fed: slow absorption, and food improves bioavailability by ~15%
# (F is a fraction and cannot exceed 1, so the increase is 0.65 -> 0.75)
ka_fed <- 0.35
F_fed  <- 0.75
C_fed <- pmax(bateman(time, D, V, ka_fed, k, Fbio = F_fed), 0)

pk_food <- bind_rows(
  data.frame(TIME = time, CONC = C_fasted, MEAL = "Fasted"),
  data.frame(TIME = time, CONC = C_fed, MEAL = "Fed")
)

pk_food %>%
  group_by(MEAL) %>%
  summarise(
    Cmax = max(CONC),
    Tmax = TIME[which.max(CONC)],
    .groups = "drop"
  )

# ----------------------------------------------------------------------
# Section: R: AUC and Fed/Fasted Ratios
# ----------------------------------------------------------------------
auc_trap <- function(t, c) {
  sum((c[-1] + c[-length(c)]) / 2 * diff(t))
}

AUC_fasted <- auc_trap(time, C_fasted)
AUC_fed <- auc_trap(time, C_fed)

data.frame(
  endpoint = c("Cmax", "AUC", "Tmax"),
  fasted = c(max(C_fasted), AUC_fasted, time[which.max(C_fasted)]),
  fed = c(max(C_fed), AUC_fed, time[which.max(C_fed)]),
  ratio_fed_fasted = c(
    max(C_fed) / max(C_fasted),
    AUC_fed / AUC_fasted,
    NA
  )
) %>%
  mutate(across(where(is.numeric), ~ round(.x, 3)))

# ----------------------------------------------------------------------
# Section: Visualization
# ----------------------------------------------------------------------
ggplot(pk_food, aes(TIME, CONC, color = MEAL)) +
  geom_line(linewidth = 0.9) +
  labs(
    x = "Time (h)", y = "Concentration (mg/L)",
    title = "Food effect: linear scale"
  ) +
  theme_bw() +
  theme(legend.position = "bottom")

ggplot(pk_food, aes(TIME, CONC, color = MEAL)) +
  geom_line(linewidth = 0.9) +
  scale_y_log10() +
  labs(
    x = "Time (h)", y = "Concentration (mg/L, log)",
    title = "Food effect: semi-log scale"
  ) +
  theme_bw() +
  theme(legend.position = "bottom")

# ----------------------------------------------------------------------
# Section: R: Simulated Crossover Food Effect Study
# ----------------------------------------------------------------------
n <- 18
set.seed(20260731)

fed_fast <- tibble(
  USUBJID = sprintf("%03d", 1:n),
  subj_eff = rnorm(n, 0, 0.2)
) %>%
  rowwise() %>%
  mutate(
    lnAUC_fasted = log(85) + subj_eff + rnorm(1, 0, 0.12),
    lnAUC_fed = log(85 * 1.10) + subj_eff + rnorm(1, 0, 0.12),
    lnCmax_fasted = log(2.5) + subj_eff + rnorm(1, 0, 0.15),
    lnCmax_fed = log(2.5 * 0.75) + subj_eff + rnorm(1, 0, 0.15)
  ) %>%
  ungroup()

# Fed/Fasted GMR and 90% CI for AUC
diff_auc <- fed_fast$lnAUC_fed - fed_fast$lnAUC_fasted
gmr_auc <- exp(mean(diff_auc))
se_auc <- sd(diff_auc) / sqrt(n)
ci_auc <- exp(mean(diff_auc) + c(-1, 1) * qt(0.95, n - 1) * se_auc)

diff_cmax <- fed_fast$lnCmax_fed - fed_fast$lnCmax_fasted
gmr_cmax <- exp(mean(diff_cmax))
ci_cmax <- exp(mean(diff_cmax) + c(-1, 1) * qt(0.95, n - 1) * sd(diff_cmax) / sqrt(n))

data.frame(
  parameter = c("AUC", "Cmax"),
  GMR_fed_fasted = round(c(gmr_auc, gmr_cmax), 3),
  CI_90_low = round(c(ci_auc[1], ci_cmax[1]), 3),
  CI_90_high = round(c(ci_auc[2], ci_cmax[2]), 3),
  significant = c(
    if_else(ci_auc[1] < 0.80 | ci_auc[2] > 1.25, "Yes", "No"),
    if_else(ci_cmax[1] < 0.80 | ci_cmax[2] > 1.25, "Yes", "No")
  )
)

