# Drug–Drug Interactions
# Extracted executable R code from 25-drug-drug-interactions.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Simulation: CL Sensitivity
# ----------------------------------------------------------------------
set.seed(20260731)
library(ggplot2)
library(dplyr)

CL_base <- 5.0   # L/h
D <- 100         # mg
tau <- 12        # h
Fbio <- 1        # named Fbio, not F, which is base R's FALSE

# CL fold-change from perpetrator
cl_fold <- seq(0.2, 3, by = 0.05)

ddi_df <- tibble(
  CL = CL_base * cl_fold,
  CL_fold = cl_fold,
  AUC_ratio = CL_base / CL,
  Css_avg = Fbio * D / (CL * tau)
)

ddi_df %>%
  filter(abs(CL_fold - 1) < 0.01 | CL_fold %in% c(0.25, 0.5, 2, 3)) %>%
  mutate(across(where(is.numeric), ~ round(.x, 3)))

# ----------------------------------------------------------------------
# Section: R: Visualize DDI Sensitivity
# ----------------------------------------------------------------------
ggplot(ddi_df, aes(CL_fold, AUC_ratio)) +
  geom_line(linewidth = 0.9, color = "firebrick") +
  geom_hline(yintercept = c(0.8, 1.25, 2, 5), linetype = "dashed", alpha = 0.6) +
  geom_vline(xintercept = 1, linetype = "dotted") +
  labs(
    x = "CL fold-change (perpetrator / control)",
    y = "AUC ratio (victim with / without perpetrator)",
    title = "DDI magnitude vs clearance change"
  ) +
  scale_x_log10() +
  theme_bw()

ggplot(ddi_df, aes(CL_fold, Css_avg)) +
  geom_line(linewidth = 0.9, color = "steelblue") +
  geom_hline(yintercept = Fbio * D / (CL_base * tau), linetype = "dashed") +
  labs(
    x = "CL fold-change",
    y = "Average steady-state concentration (mg/L)",
    title = "Steady-state exposure vs clearance"
  ) +
  theme_bw()

# ----------------------------------------------------------------------
# Section: R: Simulated DDI Crossover Study
# ----------------------------------------------------------------------
n <- 16
set.seed(20260731)

# True DDI: 60% CL reduction → AUC ratio = 1/0.4 = 2.5
cl_ddi_fold <- 0.4
true_auc_ratio <- 1 / cl_ddi_fold

ddi_study <- tibble(
  USUBJID = sprintf("%03d", 1:n),
  subj_eff = rnorm(n, 0, 0.18)
) %>%
  rowwise() %>%
  mutate(
    lnAUC_control = log(50) + subj_eff + rnorm(1, 0, 0.10),
    lnAUC_ddi = log(50 * true_auc_ratio) + subj_eff + rnorm(1, 0, 0.10)
  ) %>%
  ungroup()

diff_ln <- ddi_study$lnAUC_ddi - ddi_study$lnAUC_control
gmr <- exp(mean(diff_ln))
ci <- exp(mean(diff_ln) + c(-1, 1) * qt(0.95, n - 1) * sd(diff_ln) / sqrt(n))

data.frame(
  true_AUC_ratio = true_auc_ratio,
  observed_GMR = round(gmr, 2),
  CI_90 = paste0("[", round(ci[1], 2), ", ", round(ci[2], 2), "]"),
  classification = "Moderate inhibition"   # GMR ~2.5 falls in the 2-5 band
)

