# Special Populations
# Extracted executable R code from 26-special-populations.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Example: Renal Function and Clearance
# ----------------------------------------------------------------------
set.seed(20260731)
library(ggplot2)
library(dplyr)

# Drug with 70% renal elimination at normal renal function
CL_ref <- 7.2     # L/h total clearance at CLcr = 100 mL/min
f_r <- 0.70       # fraction of CL_ref that is renal
CL_cr_ref <- 100  # mL/min reference

cl_renal <- function(clcr) {
  CL_ref * ((1 - f_r) + f_r * clcr / CL_cr_ref)
}

clcr_range <- seq(5, 120, by = 1)
renal_df <- tibble(
  CLcr = clcr_range,
  CL = cl_renal(clcr_range),
  AUC_ratio = cl_renal(CL_cr_ref) / CL
)

renal_df %>%
  filter(CLcr %in% c(120, 60, 30, 15)) %>%
  mutate(across(where(is.numeric), ~ round(.x, 2)))

# ----------------------------------------------------------------------
# Section: R: Renal Dose Adjustment Plot
# ----------------------------------------------------------------------
ggplot(renal_df, aes(CLcr, AUC_ratio)) +
  geom_line(linewidth = 0.9, color = "darkgreen") +
  geom_hline(yintercept = c(1, 1.25, 1.5, 2), linetype = "dashed", alpha = 0.5) +
  labs(
    x = "Creatinine clearance (mL/min)",
    y = "AUC ratio vs normal renal function",
    title = "Exposure increase as renal function declines"
  ) +
  theme_bw()

# ----------------------------------------------------------------------
# Section: R Example: Allometric Scaling
# ----------------------------------------------------------------------
library(readr)

pk_oral <- read_csv("data/pk_oral_multi.csv", show_col_types = FALSE)

# Adult reference
WT_std <- 70  # kg
CL_std <- 5.0 # L/h (hypothetical adult CL)

# Allometric CL prediction for each subject
pk_scaled <- pk_oral %>%
  distinct(USUBJID, WT) %>%
  mutate(
    CL_pred = CL_std * (WT / WT_std)^0.75,
    V_pred = 30 * (WT / WT_std)^1.0,
    t_half_pred = 0.693 * V_pred / CL_pred
  )

pk_scaled %>%
  summarise(
    WT_min = min(WT),
    WT_max = max(WT),
    CL_min = min(CL_pred),
    CL_max = max(CL_pred),
    t_half_range = paste0(round(min(t_half_pred), 1), "–", round(max(t_half_pred), 1), " h")
  )

# ----------------------------------------------------------------------
# Section: R: Toy Dose Adjustment
# ----------------------------------------------------------------------
# Scenario: elderly patient with reduced CL_cr
D_standard <- 500  # mg q12h
CL_cr_patient <- 25  # mL/min
CL_cr_normal <- 100

CL_normal <- cl_renal(CL_cr_normal)
CL_patient <- cl_renal(CL_cr_patient)

# Maintain same AUC: D_new = D_standard * (CL_patient / CL_normal)
D_adjusted <- D_standard * (CL_patient / CL_normal)

# Alternative: extend dosing interval
tau_standard <- 12
tau_adjusted <- tau_standard * (CL_normal / CL_patient)

data.frame(
  CL_cr_patient = CL_cr_patient,
  CL_normal = round(CL_normal, 2),
  CL_patient = round(CL_patient, 2),
  D_standard_mg = D_standard,
  D_adjusted_mg = round(D_adjusted, 0),
  tau_standard_h = tau_standard,
  tau_adjusted_h = round(tau_adjusted, 1),
  AUC_ratio_if_no_change = round(CL_normal / CL_patient, 2)
)

# ----------------------------------------------------------------------
# Section: Beyond Fixed-Exponent Allometry
# ----------------------------------------------------------------------
# Maturational allometry: CL vs postmenstrual age at fixed weight
maturation <- function(PMA, PM50 = 46, H = 3) PMA^H / (PMA^H + PM50^H)
CL_allometric <- 8 * (10/70)^0.75   # size-adjusted 'mature' CL for a 10 kg child
PMA_grid <- seq(25, 140, by = 5)
tibble(PMA = PMA_grid,
       CL_allometric = CL_allometric,
       CL_matured = CL_allometric * maturation(PMA_grid),
       maturation_fraction = maturation(PMA_grid)) %>%
  filter(PMA %in% c(25, 35, 45, 60, 100)) %>%
  mutate(across(-PMA, ~ round(.x, 3)))

