# Therapeutic Drug Monitoring
# Extracted executable R code from 27-therapeutic-drug-monitoring.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: R Example: Steady-State Trough Simulation
# ----------------------------------------------------------------------
set.seed(20260731)
library(ggplot2)
library(dplyr)
library(tidyr)

# One-compartment oral repeated dosing
D <- 200      # mg
tau <- 12     # h
Fbio <- 0.9   # named Fbio, not F, which is base R's FALSE
V <- 25       # L
k <- 0.15     # h^-1
CL <- k * V

# Steady-state trough (approximate for oral)
n_doses <- 10
times <- seq(0, n_doses * tau, by = 0.1)

# Simulate accumulation with oral absorption
ka <- 0.8
oral_dose <- function(t, t_dose) {
  td <- pmax(t - t_dose, 0)
  Fbio * D * ka / (V * (ka - k)) * (exp(-k * td) - exp(-ka * td))
}

C <- rep(0, length(times))
for (d in 0:(n_doses - 1)) {
  C <- C + oral_dose(times, d * tau)
}

trough_times <- seq(tau, n_doses * tau, by = tau)
trough_idx <- sapply(trough_times, function(t) which.min(abs(times - t)))
troughs <- C[trough_idx]

data.frame(
  CL = CL,
  Css_avg = Fbio * D / (CL * tau),
  Cmin_ss_last = round(tail(troughs, 1), 3)
)

# ----------------------------------------------------------------------
# Section: R: Simple Proportional Dose Adjustment
# ----------------------------------------------------------------------
# Observed trough below target
Cmin_obs <- 1.2   # mg/L
Cmin_target <- 2.0
D_current <- 200  # mg q12h

D_new <- D_current * (Cmin_target / Cmin_obs)

data.frame(
  Cmin_obs = Cmin_obs,
  Cmin_target = Cmin_target,
  D_current = D_current,
  D_new = round(D_new, 0),
  percent_increase = round(100 * (D_new / D_current - 1), 1)
)

# ----------------------------------------------------------------------
# Section: R: Bayesian Update for Clearance
# ----------------------------------------------------------------------
# Population prior on CL (log-normal)
CL_pop <- 5.0       # L/h
CV_cl <- 0.30
log_CL_pop <- log(CL_pop)
sigma_prior <- sqrt(log(1 + CV_cl^2))  # log-scale SD

# Patient data
D_obs <- 200
tau_obs <- 12
F_obs <- 0.9
Cmin_obs <- 1.2
V_pop <- 25

# Predicted trough as function of CL (simplified).
# The trailing exp(-k * tau) is what makes this the TROUGH; without it the
# expression is the steady-state PEAK and can never fall to the observed 1.2.
predict_cmin <- function(cl) {
  k <- cl / V_pop
  F_obs * D_obs / (V_pop * (1 - exp(-k * tau_obs))) * exp(-k * tau_obs)
}

# Likelihood: observed Cmin with assay CV
sigma_obs <- 0.15  # log-scale or proportional error

# Grid-based posterior for CL
cl_grid <- seq(1, 15, by = 0.05)
log_cl <- log(cl_grid)

prior <- dnorm(log_cl, log_CL_pop, sigma_prior)
lik <- dnorm(Cmin_obs, predict_cmin(cl_grid), Cmin_obs * sigma_obs)
post <- prior * lik
post <- post / sum(post)

CL_map <- cl_grid[which.max(post)]
CL_mean_post <- sum(cl_grid * post)

# Dose for target trough: D_new = D_old * Cmin_target / Cmin_predicted_at_MAP
Cmin_target <- 2.0
D_bayes <- D_obs * (Cmin_target / predict_cmin(CL_map))

data.frame(
  CL_population = CL_pop,
  CL_MAP = round(CL_map, 2),
  CL_posterior_mean = round(CL_mean_post, 2),
  Cmin_predicted_at_MAP = round(predict_cmin(CL_map), 3),
  D_current = D_obs,
  D_bayesian = round(D_bayes, 0)
)

# ----------------------------------------------------------------------
# Section: R: Visualize Prior, Likelihood, Posterior
# ----------------------------------------------------------------------
post_df <- tibble(
  CL = cl_grid,
  prior = prior / max(prior),
  likelihood = lik / max(lik),
  posterior = post / max(post)
) %>%
  pivot_longer(-CL, names_to = "distribution", values_to = "density")

ggplot(post_df, aes(CL, density, color = distribution)) +
  geom_line(linewidth = 0.9) +
  geom_vline(xintercept = c(CL_pop, CL_map), linetype = "dashed", alpha = 0.5) +
  labs(
    x = "Clearance (L/h)", y = "Normalized density",
    title = "Bayesian update: prior + likelihood → posterior"
  ) +
  theme_bw() +
  theme(legend.position = "bottom")

