# Population Pharmacokinetics: Why and How
# Extracted executable R code from 28-population-pk.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Simulating a Sparse-Sampling Cohort
# ----------------------------------------------------------------------
set.seed(20260731)
library(dplyr)
library(ggplot2)

n_sub <- 40
CL_pop <- 5    # L/h
V_pop  <- 50   # L
omega_CL <- 0.25
omega_V  <- 0.20
D <- 500       # mg

# Individual parameters (log-normal IIV)
eta_CL <- rnorm(n_sub, 0, omega_CL)
eta_V  <- rnorm(n_sub, 0, omega_V)
CL_i <- CL_pop * exp(eta_CL)
V_i  <- V_pop  * exp(eta_V)
k_i  <- CL_i / V_i

# Sparse times: two per subject, staggered across cohort
time_pool <- c(0.5, 1, 2, 4, 8, 12, 24)
subj <- data.frame(
  ID = 1:n_sub,
  CL = CL_i,
  V = V_i,
  k = k_i
)

obs_list <- lapply(1:n_sub, function(i) {
  t_samp <- sample(time_pool, 2)
  C <- (D / V_i[i]) * exp(-k_i[i] * t_samp)
  C <- C * exp(rnorm(length(t_samp), 0, 0.10))  # exponential (log-normal) residual error
  data.frame(ID = i, TIME = t_samp, DV = C)
})
sparse_dat <- bind_rows(obs_list)

ggplot(sparse_dat, aes(TIME, DV)) +
  geom_point(alpha = 0.7) +
  scale_y_log10() +
  labs(
    x = "Time (h)", y = "Concentration (mg/L)",
    title = "Sparse PK samples from a simulated cohort"
  ) +
  theme_minimal()

