# Nonlinear Mixed-Effects Models for PK
# Extracted executable R code from 29-mixed-effects-models.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: nlmixr2: One-Compartment IV Bolus
# ----------------------------------------------------------------------
# [not executed in the book render — optional/heavy example]
# library(nlmixr2)
# 
# one_cpt <- function() {
#   ini({
#     lCL <- log(5)      # typical CL (L/h)
#     lV  <- log(50)     # typical V (L)
#     eta.cl ~ 0.25^2
#     eta.v  ~ 0.20^2
#     prop.sd <- 0.10
#   })
#   model({
#     cl <- exp(lCL + eta.cl)
#     v  <- exp(lV  + eta.v)
#     linCmt() ~ prop(prop.sd)
#   })
# }
# 
# # Build sparse_dat as in Chapter 29, or:
# # sparse_dat <- read.csv("data/sparse_pk.csv")
# # fit <- nlmixr2(one_cpt, sparse_dat, est = "saem",
# #               control = saemControl(nBurn = 200, nEm = 200))
# # fit

# ----------------------------------------------------------------------
# Section: Fast Simulation with Closed Form
# ----------------------------------------------------------------------
set.seed(20260731)
library(dplyr)
library(tidyr)
library(ggplot2)

n_sub <- 20
CL_pop <- 5; V_pop <- 50; D <- 500
omega_CL <- 0.25; omega_V <- 0.20

sim_subj <- tibble(
  ID = 1:n_sub,
  CL = CL_pop * exp(rnorm(n_sub, 0, omega_CL)),
  V  = V_pop  * exp(rnorm(n_sub, 0, omega_V))
) |>
  mutate(k = CL / V)

times <- seq(0, 24, by = 0.25)
sim_curves <- sim_subj |>
  tidyr::crossing(TIME = times) |>
  mutate(DV = (D / V) * exp(-k * TIME))

# Typical (population) profile
typical <- tibble(
  TIME = times,
  DV = (D / V_pop) * exp(-(CL_pop / V_pop) * TIME),
  type = "Typical"
)

ggplot(sim_curves |> filter(DV > 0), aes(TIME, DV, group = ID)) +
  geom_line(alpha = 0.4) +
  geom_line(data = typical |> filter(DV > 0), aes(TIME, DV), linewidth = 1.2,
            color = "red", inherit.aes = FALSE) +
  scale_y_log10() +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Population IV bolus: individual curves vs typical") +
  theme_minimal()

# ----------------------------------------------------------------------
# Section: Simulation with mrgsolve
# ----------------------------------------------------------------------
set.seed(20260731)
library(mrgsolve)
library(dplyr)
library(ggplot2)

code <- '
$PARAM CL = 5, V = 50
$CMT CENT
$MAIN
double ke = CL/V;
$ODE
dxdt_CENT = -ke*CENT;
$TABLE
double cp = CENT/V;
$CAPTURE cp CL V
'

mod <- mcode("onecpt", code, quiet = TRUE)

data <- mod |>
  ev(amt = 500, cmt = 1) |>
  mrgsim(end = 24, delta = 0.25) |>
  as.data.frame()

ggplot(data |> filter(cp > 0), aes(time, cp)) +
  geom_line(linewidth = 1) +
  scale_y_log10() +
  labs(x = "Time (h)", y = "cp (mg/L)", title = "mrgsolve: single-subject IV bolus") +
  theme_minimal()

