# Covariate Modeling in Population PK
# Extracted executable R code from 30-covariate-modeling.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Simulated Data and CL vs Weight Plot
# ----------------------------------------------------------------------
set.seed(20260731)
library(dplyr)
library(ggplot2)

n <- 80
WT <- rnorm(n, mean = 75, sd = 14)
WT <- pmax(WT, 45)
SEX <- sample(c("F", "M"), n, replace = TRUE)

CL_ref <- 5
theta_WT <- 0.008   # log-CL per kg above reference
WT_ref <- 70
theta_SEX <- 0.12     # males higher CL

CL <- CL_ref *
  exp(theta_WT * (WT - WT_ref)) *
  exp(theta_SEX * (SEX == "M")) *
  exp(rnorm(n, 0, 0.20))

dat <- tibble(ID = 1:n, WT, SEX, CL)

ggplot(dat, aes(WT, CL, color = SEX)) +
  geom_point(alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE, formula = y ~ x) +
  scale_y_log10() +
  labs(
    x = "Weight (kg)", y = "Clearance (L/h)",
    title = "Simulated clearance vs body weight by sex"
  ) +
  theme_minimal()

# ----------------------------------------------------------------------
# Section: Including Covariates in nlmixr2
# ----------------------------------------------------------------------
# [not executed in the book render — optional/heavy example]
# library(nlmixr2)
# 
# one_cpt_wt <- function() {
#   ini({
#     lCL <- log(5)      # typical CL at WT = 70 kg
#     lV  <- log(50)     # typical V at WT = 70 kg
#     tCL_WT <- 0.75     # allometric exponent (fixed or estimated)
#     tV_WT  <- 1.0
#     eta.cl ~ 0.25^2
#     eta.v  ~ 0.20^2
#     prop.sd <- 0.10
#   })
#   model({
#     cl <- exp(lCL + tCL_WT * log(WT / 70) + eta.cl)
#     v  <- exp(lV  + tV_WT  * log(WT / 70) + eta.v)
#     linCmt() ~ prop(prop.sd)
#   })
# }
# 
# # fit <- nlmixr2(one_cpt_wt, sparse_dat, est = "saem")

