# Clinical Trial Simulation from Population PK
# Extracted executable R code from 32-simulation.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: mrgsolve: Two Regimens
# ----------------------------------------------------------------------
set.seed(20260731)
library(mrgsolve)
library(dplyr)
library(ggplot2)

code <- '
$PARAM CL = 5, V = 50
$CMT CENT
$MAIN
double ke = CL/V;
$ODE
dxdt_CENT = -ke*CENT;
$TABLE
double cp = CENT/V;
$CAPTURE cp
'

mod <- mcode("sim1cpt", code, quiet = TRUE)

# Regimen A: 500 mg q24h x 7 days
ev_qd <- mod |>
  ev(amt = 500, ii = 24, addl = 6) |>
  mrgsim(end = 168, delta = 0.5)

# Regimen B: 250 mg q12h x 7 days
ev_bid <- mod |>
  ev(amt = 250, ii = 12, addl = 13) |>
  mrgsim(end = 168, delta = 0.5)

plot_dat <- bind_rows(
  as.data.frame(ev_qd) |> mutate(regimen = "500 mg q24h"),
  as.data.frame(ev_bid) |> mutate(regimen = "250 mg q12h")
)

ggplot(plot_dat |> filter(cp > 0), aes(time, cp, color = regimen)) +
  geom_line(linewidth = 0.9) +
  scale_y_log10() +
  labs(x = "Time (h)", y = "Concentration (mg/L)",
       title = "Steady-state comparison: q24h vs q12h") +
  theme_minimal()

# ----------------------------------------------------------------------
# Section: Population Simulation and PTA
# ----------------------------------------------------------------------
set.seed(20260731)

n_sim <- 500
CL_pop <- 5; V_pop <- 50
omega_CL <- 0.30
D <- 500; tau <- 24

# Closed-form steady-state trough after repeated IV bolus
trough <- numeric(n_sim)
for (i in 1:n_sim) {
  CLi <- CL_pop * exp(rnorm(1, 0, omega_CL))
  ki  <- CLi / V_pop
  # Cmin,ss = (D/V) * exp(-k*tau) / (1 - exp(-k*tau))
  trough[i] <- (D / V_pop) * exp(-ki * tau) / (1 - exp(-ki * tau))
}

target <- 1.0
PTA <- mean(trough >= target)

tibble(trough = trough) |>
  ggplot(aes(trough)) +
  geom_histogram(bins = 40, fill = "steelblue", alpha = 0.8) +
  geom_vline(xintercept = target, color = "red", linetype = 2) +
  annotate("text", x = target + 0.3, y = Inf, vjust = 2,
           label = sprintf("PTA = %.1f%%", 100 * PTA)) +
  labs(x = "Ctrough (mg/L)", y = "Count",
       title = "Simulated trough distribution and PTA") +
  theme_minimal()

# ----------------------------------------------------------------------
# Section: rxode2 Alternative
# ----------------------------------------------------------------------
set.seed(20260731)
library(rxode2)

mod_rx <- rxode2({
  d/dt(cent) = -(CL/V) * cent
  cp = cent / V
})

ev1 <- et(amt = 500, ii = 24, addl = 6)
ev1 <- et(ev1, seq(0, 168, by = 0.5))

x <- rxSolve(mod_rx, params = c(CL = 5, V = 50), events = ev1)
plot(x$time, x$cp, type = "l", log = "y",
     xlab = "Time (h)", ylab = "cp (mg/L)",
     main = "rxode2: repeated dosing")

