# Exposure–Response Relationships
# Extracted executable R code from 33-exposure-response.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Simulating and Plotting $E_{\max}$
# ----------------------------------------------------------------------
set.seed(20260731)
library(dplyr)
library(ggplot2)

E0 <- 10
Emax <- 80
EC50 <- 5

emax_fn <- function(C, E0, Emax, EC50) {
  E0 + Emax * C / (EC50 + C)
}

C_grid <- seq(0, 40, length.out = 200)
curve_df <- tibble(C = C_grid, E = emax_fn(C, E0, Emax, EC50))

# Simulated trial subjects
n <- 40
subj <- tibble(
  ID = 1:n,
  AUC = rlnorm(n, log(8), 0.35)
) |>
  mutate(
    E_true = emax_fn(AUC, E0, Emax, EC50),
    E_obs = E_true + rnorm(n, 0, 5)
  )

fit_nls <- nls(
  E_obs ~ E0_hat + Emax_hat * AUC / (EC50_hat + AUC),
  data = subj,
  start = list(E0_hat = 10, Emax_hat = 80, EC50_hat = 5)
)
fit_coef <- coef(fit_nls)
fit_df <- tibble(
  C = C_grid,
  E = emax_fn(C_grid, fit_coef[["E0_hat"]], fit_coef[["Emax_hat"]],
              fit_coef[["EC50_hat"]])
)

ggplot(subj, aes(AUC, E_obs)) +
  geom_point(alpha = 0.7) +
  geom_line(data = curve_df, aes(C, E), linewidth = 1.1, color = "darkred",
            inherit.aes = FALSE) +
  geom_line(data = fit_df, aes(C, E), linewidth = 1, color = "steelblue",
            linetype = 2, inherit.aes = FALSE) +
  labs(x = "AUC (mg*h/L)", y = "Effect (units)",
       title = "Emax exposure-response: truth (solid) and nls fit (dashed)") +
  theme_minimal()

