# Pharmacodynamic Models
# Extracted executable R code from 34-pharmacodynamics.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: deSolve: Indirect Response Simulation
# ----------------------------------------------------------------------
set.seed(20260731)
library(deSolve)
library(dplyr)
library(ggplot2)

pkpd <- function(t, state, parms) {
  with(as.list(c(state, parms)), {
    dA <- -k * A
    C  <- A / V
    I  <- Imax * C / (IC50 + C)
    dR <- kin * (1 - I) - kout * R
    list(c(dA, dR))
  })
}

parms <- c(k = 0.1, V = 50, kin = 10, kout = 0.5,
           Imax = 0.9, IC50 = 2)
state <- c(A = 500, R = 20)  # R0 = kin/kout = 20

times <- seq(0, 72, by = 0.1)
out <- ode(y = state, times = times, func = pkpd, parms = parms)

df <- as.data.frame(out) |>
  mutate(C = A / parms["V"])

ggplot(df, aes(time)) +
  geom_line(aes(y = C, color = "Concentration")) +
  geom_line(aes(y = R, color = "Response")) +
  scale_color_manual(values = c("Concentration" = "steelblue", "Response" = "darkorange")) +
  labs(x = "Time (h)", y = "Value", color = NULL,
       title = "Indirect response: inhibition of kin") +
  theme_minimal()

