# Integrated PK/PD Models
# Extracted executable R code from 35-pk-pd-models.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Simulation: PK Driving Effect Compartment PD
# ----------------------------------------------------------------------
set.seed(20260731)
library(deSolve)
library(dplyr)
library(ggplot2)

pkpd_ec <- function(t, state, parms) {
  with(as.list(c(state, parms)), {
    Cp <- A / V
    dGut <- -ka * Gut
    dA <- ka * Gut - k * A
    dCe <- ke0 * (Cp - Ce)
    E <- E0 + Emax * Ce / (EC50 + Ce)
    list(c(dGut, dA, dCe), E = E)
  })
}

parms <- c(ka = 1.0, k = 0.12, V = 40, ke0 = 0.08,
           E0 = 5, Emax = 90, EC50 = 1.5)
state <- c(Gut = 400, A = 0, Ce = 0)

times <- seq(0, 48, by = 0.05)
out <- ode(y = state, times = times, func = pkpd_ec, parms = parms)

df <- as.data.frame(out) |>
  mutate(Cp = A / parms["V"]) |>
  filter(Cp > 0, Ce > 0)

# Hysteresis plot
p1 <- ggplot(df, aes(Cp, E)) +
  geom_path(arrow = arrow(length = unit(0.15, "cm")), linewidth = 0.8) +
  scale_x_log10() +
  labs(x = "Plasma C (mg/L)", y = "Effect",
       title = "Hysteresis: E vs Cp") +
  theme_minimal()

# Collapsed with effect compartment
p2 <- ggplot(df, aes(Ce, E)) +
  geom_point(size = 0.8, alpha = 0.6) +
  scale_x_log10() +
  labs(x = "Effect-site Ce (mg/L)", y = "Effect",
       title = "E vs Ce (loop collapsed)") +
  theme_minimal()

print(p1)
print(p2)

