# Bayesian Pharmacokinetics
# Extracted executable R code from 36-bayesian-pharmacokinetics.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Grid Posterior for Clearance
# ----------------------------------------------------------------------
set.seed(20260731)
library(dplyr)
library(ggplot2)

# One-compartment IV: C(t) = (D/V) exp(-CL/V * t)
D <- 500; V <- 50
t_obs <- 4  # single sample: posterior is a compromise between prior and data
CL_true <- 6

C_true <- (D / V) * exp(-CL_true / V * t_obs)
Y_obs <- C_true * exp(rnorm(1, 0, 0.08))

# Prior: lognormal-ish on CL (log scale normal)
CL_grid <- seq(2, 12, length.out = 400)
prior <- dlnorm(CL_grid, meanlog = log(5), sdlog = 0.25)

# Proportional likelihood
lik <- sapply(CL_grid, function(cl) {
  pred <- (D / V) * exp(-cl / V * t_obs)
  dnorm(Y_obs, mean = pred, sd = pred * 0.10)
})

post <- prior * lik
post <- post / sum(post * (CL_grid[2] - CL_grid[1]))  # normalize

post_mode <- CL_grid[which.max(post)]
prior_mode <- CL_grid[which.max(prior)]

post_df <- tibble(CL = CL_grid, density = post)

ggplot(post_df, aes(CL, density)) +
  geom_line(linewidth = 1) +
  geom_vline(xintercept = CL_true, linetype = 2, color = "red") +
  geom_vline(xintercept = post_mode, color = "blue") +
  geom_vline(xintercept = prior_mode, linetype = 3, color = "gray40") +
  labs(x = "CL (L/h)", y = "Posterior density",
       title = "Grid posterior for CL (one observation; MAP between prior and data)") +
  theme_minimal()

