# Machine Learning in Pharmacokinetics
# Extracted executable R code from 37-machine-learning.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Simulated Comparison: Linear vs Random Forest
# ----------------------------------------------------------------------
set.seed(20260731)
library(dplyr)
library(ggplot2)

n <- 200
# True E-R: Emax on AUC
AUC <- rlnorm(n, log(10), 0.4)
E <- 15 + 70 * AUC / (8 + AUC) + rnorm(n, 0, 4)

dat <- tibble(AUC, E, logAUC = log(AUC))
idx <- sample(1:n, size = floor(0.7 * n))
train <- dat[idx, ]
test  <- dat[-idx, ]

# Linear model on log AUC
fit_lm <- lm(E ~ logAUC, data = train)
pred_lm <- predict(fit_lm, newdata = test)

# Simple "black box": random forest if available, else a flexible quadratic lm
has_rf <- requireNamespace("randomForest", quietly = TRUE)
if (has_rf) {
  fit_rf <- randomForest::randomForest(E ~ AUC, data = train, ntree = 200)
  pred_rf <- predict(fit_rf, newdata = test)
} else {
  # Fallback: quadratic lm as flexible-ish baseline
  fit_rf <- lm(E ~ AUC + I(AUC^2), data = train)
  pred_rf <- predict(fit_rf, newdata = test)
}

rmse <- function(y, yhat) sqrt(mean((y - yhat)^2))

results <- tibble(
  model = c("Linear (log AUC)", if (has_rf) "Random forest" else "Quadratic lm"),
  RMSE = c(rmse(test$E, pred_lm), rmse(test$E, pred_rf))
)
print(results)

ggplot(test, aes(AUC, E)) +
  geom_point(alpha = 0.6) +
  geom_line(data = tibble(
    AUC = seq(min(test$AUC), max(test$AUC), length.out = 100),
    E = predict(fit_lm, newdata = tibble(
      logAUC = log(seq(min(test$AUC), max(test$AUC), length.out = 100))
    ))
  ), aes(AUC, E), color = "blue", linewidth = 1) +
  labs(title = "Hold-out test: linear log-AUC model",
       x = "AUC", y = "Effect") +
  theme_minimal()

