# R Reference for PK Analysis
# Extracted executable R code from appendix-b-r-reference.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: deSolve
# ----------------------------------------------------------------------
set.seed(20260731)
library(deSolve)

mod <- function(t, y, parms) {
  with(as.list(c(y, parms)), {
    dA1 <- -k12 * A1 + k21 * A2 - k10 * A1
    dA2 <- k12 * A1 - k21 * A2
    list(c(dA1, dA2))
  })
}
y0 <- c(A1 = 100, A2 = 0)
out <- ode(y0, times = seq(0, 24, 0.1), mod,
           parms = c(k10 = 0.08, k12 = 0.2, k21 = 0.15))
head(out)

# ----------------------------------------------------------------------
# Section: rxode2
# ----------------------------------------------------------------------
set.seed(20260731)
library(rxode2)

mod <- rxode2({
  d/dt(cent) = -(CL/V) * cent
  cp = cent / V
})
ev <- et(amt = 500, cmt = 1)
ev <- et(ev, seq(0, 24, 0.25))
x <- rxSolve(mod, params = c(CL = 5, V = 50), events = ev)
head(as.data.frame(x))

# ----------------------------------------------------------------------
# Section: mrgsolve
# ----------------------------------------------------------------------
set.seed(20260731)
library(mrgsolve)

code <- '
$PARAM CL = 5, V = 50, KA = 0.5
$CMT GUT CENT
$MAIN
double ke = CL/V;
$ODE
dxdt_GUT  = -KA*GUT;
dxdt_CENT =  KA*GUT - ke*CENT;
$TABLE
double cp = CENT/V;
$CAPTURE cp
'
mod <- mcode("oral1", code, quiet = TRUE)
out <- mod |> ev(amt = 500, cmt = 1) |> mrgsim(end = 24, delta = 0.25)
head(as.data.frame(out))

# ----------------------------------------------------------------------
# Section: PKNCA (NCA)
# ----------------------------------------------------------------------
# [not executed in the book render — optional/heavy example]
# # library(PKNCA)
# # d_conc <- as.data.frame(datasets::Theoph)
# # d_dose <- d_conc[d_conc$Time == 0, c("Dose", "Time", "Subject")]
# # conc_obj <- PKNCAconc(d_conc, conc ~ Time | Subject)
# # dose_obj <- PKNCAdose(d_dose, Dose ~ Time | Subject)
# # data_obj <- PKNCAdata(conc_obj, dose_obj)
# # results <- pk.nca(data_obj)
# # summary(results)

# ----------------------------------------------------------------------
# Section: nlmixr2
# ----------------------------------------------------------------------
# [not executed in the book render — optional/heavy example]
# # library(nlmixr2)
# # mod <- function() {
# #   ini({
# #     lCL <- log(5); lV <- log(50)
# #     eta.cl ~ 0.2^2; eta.v ~ 0.2^2
# #     prop.sd <- 0.1
# #   })
# #   model({
# #     cl <- exp(lCL + eta.cl)
# #     v  <- exp(lV  + eta.v)
# #     linCmt() ~ prop(prop.sd)
# #   })
# # }
# # fit <- nlmixr2(mod, mydata, est = "saem")

# ----------------------------------------------------------------------
# Section: ggplot2 PK Plots
# ----------------------------------------------------------------------
set.seed(20260731)
library(dplyr)
library(ggplot2)

dat <- tibble(
  TIME = rep(c(0, 1, 2, 4, 8), 3),
  DV = c(0, 7, 6.5, 4, 2, 0, 8, 7, 5, 2.5, 0, 9, 8, 6, 3),
  ID = rep(1:3, each = 5)
)

ggplot(dat |> filter(DV > 0), aes(TIME, DV, color = factor(ID))) +
  geom_line() + geom_point() +
  scale_y_log10() +
  labs(x = "Time (h)", y = "Concentration (mg/L)") +
  theme_minimal()

# Observed vs predicted (popPK GOF)
ggplot(dat, aes(DV, DV * runif(nrow(dat), 0.9, 1.1))) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  labs(x = "Observed", y = "Predicted") +
  theme_minimal()

