# Statistical Methods for PK
# Extracted executable R code from appendix-c-statistics.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Bootstrap Standard Error (Sketch)
# ----------------------------------------------------------------------
set.seed(20260731)

# Simulate a noisy log-linear profile and fit k
t <- c(0.5, 1, 2, 4, 8, 12, 24)
k_true <- 0.1
logC <- log(10) - k_true * t + rnorm(length(t), 0, 0.15)

fit <- lm(logC ~ t)
pred <- fitted(fit)
res  <- residuals(fit)

# Parametric/residual bootstrap: resample residuals onto the fitted curve, refit
boot_k <- replicate(500, {
  y_star <- pred + sample(res, replace = TRUE)
  -coef(lm(y_star ~ t))[2]
})

se_boot <- sd(boot_k)
ci_boot <- quantile(boot_k, c(0.025, 0.975))
c(SE = se_boot, CI_low = ci_boot[1], CI_high = ci_boot[2],
  SE_analytic = summary(fit)$coefficients[2, 2])

