# Mathematical Methods
# Extracted executable R code from appendix-a-mathematics.qmd
# Generated by scripts/extract_code.R — do not edit by hand.
# Regenerate: Rscript scripts/extract_code.R   (book repo)
#             Rscript scripts/extract_code.R --standalone   (bundle)
# Working directory: run from the repository root (data/ paths are relative).

# ----------------------------------------------------------------------
# Section: Trapezoidal Rule
# ----------------------------------------------------------------------
set.seed(20260731)
t <- c(0, 0.5, 1, 2, 4, 8, 12, 24)
C <- c(0, 8, 9.5, 8, 5, 2.5, 1.2, 0.3)
trap <- sum(diff(t) * (head(C, -1) + tail(C, -1)) / 2)
trap

# ----------------------------------------------------------------------
# Section: Euler vs Runge–Kutta
# ----------------------------------------------------------------------
set.seed(20260731)
library(deSolve)

one_cpt <- function(t, y, parms) list(-parms["k"] * y)
y0 <- 10; times <- seq(0, 24, by = 0.01)
out_euler <- ode(y0, times, one_cpt, parms = c(k = 0.1), method = "euler")
out_rk    <- ode(y0, times, one_cpt, parms = c(k = 0.1), method = "rk4")
max(abs(out_euler[, 2] - 10 * exp(-0.1 * times)))  # Euler error vs analytic
max(abs(out_rk[, 2] - 10 * exp(-0.1 * times)))     # RK4 much smaller

